// Real, publicly-sourced facility listings.
// All entries are UNVERIFIED until manually confirmed by the ElderMatch team.
// "N/A" is used verbatim wherever public information was unavailable.

export type RealFacilitySpec = {
  id: string;
  name: string;
  neighborhood: string;
  city: string;
  state: string;
  address: string;
  phone?: string;
  email?: string;
  website?: string;
  tier: "NGO/Free care" | "Budget/Private" | "Mid-range assisted living" | "Premium/Medical care";
  tierLabel: string;
  careTypes: string[];
  conditionCare: string[];
  priceMin: number;
  priceMax: number;
  priceNote: string;
  deposit: string;
  amenities: string[];
  staffRatio: string;
  hospitalTieUp: string;
  distanceToHospital: string;
  distanceToAirport: string;
  cuisine: string[];
  dietary: string[];
  languages: string[];
  licensing: string[];
  rating: number;
  reviewCount: number;
  source: string;
  description: string;
};

const NA = "N/A";

export const REAL_FACILITY_SPECS: RealFacilitySpec[] = [
  {
    id: "athulya-pallavaram-chennai",
    name: "Athulya Senior Care — Pallavaram",
    neighborhood: "Pallavaram",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "Tower C, Olympia Grande, No.328, GST Road, Pallavaram, Chennai 600043",
    phone: "98846 39400",
    email: "response@athulyaseniorcare.com",
    website: "athulyaseniorcare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Transition care",
      "Rehabilitation / Physiotherapy",
      "Palliative care",
      "Home care",
    ],
    conditionCare: [
      "Dementia/Alzheimer's (specialist team)",
      "Post-surgery / transition care",
      "Palliative care",
      "Bedridden care",
    ],
    priceMin: 55000,
    priceMax: 65000,
    priceNote: "₹55,000–65,000/month (varies by branch and room type). Extras: N/A",
    deposit: NA,
    amenities: [
      "Housekeeping & laundry",
      "In-house salon",
      "Transportation",
      "Hospital & banking coordination",
      "24/7 security + CCTV",
      "Power backup",
      "Wi-Fi",
      "Adjustable beds",
      "Nurse call bells",
      "Anti-skid flooring",
    ],
    staffRatio: NA,
    hospitalTieUp: "MoU with SingHealth",
    distanceToHospital: NA,
    distanceToAirport: "Near Chennai International Airport (exact km N/A)",
    cuisine: ["Personalized / nutritionist-managed meals"],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: ["NABH/JCI-inspired standards referenced, not formally confirmed"],
    rating: 4.4,
    reviewCount: 224,
    source: "athulyaseniorcare.com; zenioro.com",
    description:
      "Premium assisted living and memory care on GST Road, with transition care, rehabilitation and palliative services.",
  },
  {
    id: "ashiana-shubham-chennai",
    name: "Ashiana Shubham",
    neighborhood: "Maraimalai Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "Ashiana Shubham, GST Road, Maraimalai Nagar, Chennai",
    website: "ashianahousing.com",
    tier: "Premium/Medical care",
    tierLabel: "Mid-range to Premium (ownership / real-estate model)",
    careTypes: ["Independent living", "Assisted living"],
    conditionCare: [NA],
    priceMin: 14000,
    priceMax: 29000,
    priceNote:
      "Purchase ₹40.96L–83.92L (up to ₹1.25 Cr); rental ₹14,000–29,000/month. Extras: I&BA ~₹36/sq ft, activity centre ~₹86,250 one-time.",
    deposit: "Management deposit ~₹80/sq ft",
    amenities: [
      "Clubhouse",
      "Swimming pool",
      "Walking tracks",
      "24/7 security + CCTV",
      "Wheelchair accessibility",
      "Worship hall",
      "Lawn tennis",
      "Billiards",
      "Library",
      "Media hall",
      "Vegetarian cafe",
      "Multipurpose hall",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["Vegetarian cafe (no other community catering confirmed)"],
    dietary: ["Vegetarian (general)"],
    languages: [NA],
    licensing: ["N/A (real estate project, not a licensed care facility)"],
    rating: 0,
    reviewCount: 0,
    source: "ashianahousing.com; houssed.com",
    description:
      "An ownership-model senior living township on GST Road with an on-site Assisted Living Care Centre.",
  },
  {
    id: "anandam-community-chennai",
    name: "Anandam Community — A Free Home for Senior Citizens",
    neighborhood: "Ambattur",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "Anna Main Road, Gangai Nagar, Kallikuppam, Ambattur, Chennai 600053",
    phone: "044-26860099 (10am–5pm)",
    email: "anandamtrust2003@gmail.com",
    website: "anandamoldagehome.org",
    tier: "NGO/Free care",
    tierLabel: "NGO/Free",
    careTypes: ["Residential old-age home", "Assisted living"],
    conditionCare: ["General elder care; medical care via partner hospitals"],
    priceMin: 0,
    priceMax: 0,
    priceNote:
      "Free (donation-based). Eligibility: no living children, no income, above 60 years.",
    deposit: NA,
    amenities: [
      "Meals (tea/coffee, kanchi, lunch, dinner)",
      "Medical care",
      "Attached bath/toilet rooms",
      "Volunteer doctors & teachers",
    ],
    staffRatio: NA,
    hospitalTieUp:
      "Sri Ramachandra Hospital, Meenakshi Ammal Dental College, Aravind Eye Hospital, Dr. Rangarajan Memorial Hospital, Astra Hearing Care",
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["General vegetarian Indian meals"],
    dietary: ["Vegetarian (general)"],
    languages: ["Tamil"],
    licensing: ["Registered Trust (est. 2003)"],
    rating: 4.4,
    reviewCount: 224,
    source: "anandamoldagehome.org; justdial.com",
    description:
      "A free, donation-run residential home in Ambattur for senior citizens with no family support or income.",
  },
  {
    id: "covaicare-urbana-irene-bengaluru",
    name: "CovaiCare — Urbana Irene",
    neighborhood: "Devanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Urbana Irene, Ozone Urbana township (185-acre), Devanahalli, Bengaluru",
    website: "covaicare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living", "Assisted living", "Palliative care"],
    conditionCare: [
      "Assisted care (short & long term)",
      "Physiotherapy / rehabilitation",
      "Palliative / end-of-life care",
      "Special needs adult (PsWD) care",
    ],
    priceMin: 0,
    priceMax: 0,
    priceNote: "Apartments from ~₹74.12 Lakhs. Rental / care package pricing: N/A",
    deposit: NA,
    amenities: [
      "Clubhouse",
      "Landscaped gardens",
      "Cycling track",
      "Sports facilities",
      "Pressalit Care (Denmark) bathroom fittings",
      "20,000 sq ft Services & Care Facility floor",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: "Near Kempegowda International Airport (exact km N/A)",
    cuisine: ["Community catering service (details N/A)"],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "covaicare.com; elkin.co.in",
    description:
      "Independent living apartments inside Ozone Urbana with an on-site Services & Care Facility for assisted and palliative care.",
  },
  {
    id: "nightingales-medical-trust-bengaluru",
    name: "Nightingales Medical Trust",
    neighborhood: "RT Nagar / Kasturi Nagar",
    city: "Bengaluru",
    state: "Karnataka",
    address:
      "8P6, 3rd A Cross, Kasturinagar, Banaswadi, Bengaluru 560043; also No.337, 2nd Cross, 1st Block, RT Nagar, Bengaluru 560032",
    phone: "080-4242 6565 (24-hr)",
    email: "nmt_rtnagar@nightingaleseldercare.com",
    website: "nightingaleseldercare.com",
    tier: "NGO/Free care",
    tierLabel: "NGO (not-for-profit)",
    careTypes: ["Assisted living", "Memory/dementia care", "Palliative care", "Day care"],
    conditionCare: [
      "Dementia/Alzheimer's (core focus)",
      "Elder abuse support",
      "Active ageing programmes",
    ],
    priceMin: 0,
    priceMax: 0,
    priceNote: "N/A publicly disclosed",
    deposit: NA,
    amenities: [
      "Day care activities",
      "Exercise programmes",
      "Festival celebrations",
      "Caregiver training",
      "Dementia support groups",
    ],
    staffRatio: NA,
    hospitalTieUp:
      "N/A named; runs Elders Helpline (1090) and National Helpline (14567) for Karnataka",
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: ["Registered Trust since 1998"],
    rating: 4.6,
    reviewCount: 118,
    source: "nightingaleseldercare.com; dementiacarenotes.in",
    description:
      "A long-running Bengaluru trust offering dementia clinics, day care, assisted living and palliative care.",
  },
  {
    id: "athashri-whitefield-bengaluru",
    name: "Athashri Senior Living — Whitefield",
    neighborhood: "Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Athashri Road, Whitefield, Bengaluru, Karnataka",
    website: "pscl.in/athashri",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living", "Assisted living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: "1BHK/2BHK apartments ₹32L–65L+; maintenance charges vary.",
    deposit: NA,
    amenities: [
      "24hr power backup",
      "Clubhouse",
      "Gym",
      "Landscaped garden",
      "Library",
      "Lift",
      "Rainwater harvesting",
      "Security",
      "Wide doorways",
      "Panic buttons",
      "Grab rails",
      "Non-skid floors",
      "Stretcher lifts",
      "Video door phones",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: "Near Bangalore International Airport (exact km N/A)",
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: ["N/A (real estate / ownership project)"],
    rating: 0,
    reviewCount: 0,
    source: "pscl.in/athashri; commonfloor.com",
    description:
      "Senior-specific apartments in Whitefield with an assisted-living arm, 'Aastha', on the same campus.",
  },
  {
    id: "primus-reflection-bengaluru",
    name: "Primus Senior Living — Reflection",
    neighborhood: "Kaggalipura, Kanakapura Road",
    city: "Bengaluru",
    state: "Karnataka",
    address:
      "Kaggalipura, Kanakapura Road, Opp. Art of Living Center, Bengaluru 560082",
    website: "primuslife.in",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: ["Independent living", "Assisted living"],
    conditionCare: [
      "Medication reminders",
      "Emergency response",
      "Physiotherapy",
      "Specialist consultations",
    ],
    priceMin: 0,
    priceMax: 0,
    priceNote: "Apartments ₹47L–93L+ depending on project and BHK type.",
    deposit: NA,
    amenities: [
      "24/7 medical care / on-campus clinic",
      "Nursing staff",
      "Physiotherapy",
      "Concierge",
      "Swimming pool",
      "Tennis court",
      "Library",
      "Gym",
      "In-house restaurant",
      "Anti-skid floors",
      "Grab bars",
      "Emergency buttons",
      "Smart home features",
    ],
    staffRatio: NA,
    hospitalTieUp: "'Proximity to hospitals' mentioned generally",
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["In-house restaurant; meals designed for senior dietary needs"],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "primuslife.in; jeevinseniorcare.in",
    description:
      "A luxury senior living community on Kanakapura Road with an on-campus clinic and full concierge services.",
  },
  {
    id: "ashley-care-homes-bengaluru",
    name: "Ashley Care Homes",
    neighborhood: "Kalkere, Horamavu",
    city: "Bengaluru",
    state: "Karnataka",
    address:
      "Ashley Care Homes, 2nd floor, MR Complex, Rajkumar Layout, Kalkere, Bengaluru, Karnataka 560113",
    phone: "9731617730 / 9880763745",
    email: "ashleycarehomes@gmail.com",
    website: "ashleycarehomes.in",
    tier: "Budget/Private",
    tierLabel: "Budget to Mid-range",
    careTypes: [
      "Assisted living",
      "Nursing care",
      "Palliative care",
      "Rehabilitation / Physiotherapy",
    ],
    conditionCare: [
      "Bedridden patients (since 2009)",
      "Stroke / frozen shoulder / arthritis rehab",
      "Palliative care",
      "Post-operative care",
      "Cardiac rehabilitation",
    ],
    priceMin: 0,
    priceMax: 0,
    priceNote: "N/A publicly disclosed",
    deposit: NA,
    amenities: [
      "24/7 nursing",
      "Timely medication",
      "Nutrition support",
      "Creative & cognitive activities",
      "Yoga",
      "Music therapy",
      "Games",
    ],
    staffRatio: "Claims 'high ratio' — no number given",
    hospitalTieUp: NA,
    distanceToHospital: "'Near Hebbal', 'near Sarjapur Road' — no exact km",
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: ["Listed as 'Government Approved' (unverified)"],
    rating: 4.1,
    reviewCount: 163,
    source: "justdial.com; ashleycarehomes.in",
    description:
      "A budget-to-mid-range Bengaluru care home focused on bedridden, post-operative and palliative residents.",
  },
  {
    id: "kadji-care-vadodara",
    name: "Kadji Care",
    neighborhood: "Kalali",
    city: "Vadodara",
    state: "Gujarat",
    address:
      "Kadji Road, next to Delhi Public School, Vadsar, Kalali, Vadodara, Gujarat 390020",
    phone: "Ends in 0406 (masked)",
    website: "kadjicare (verify exact URL)",
    tier: "Mid-range assisted living",
    tierLabel: "Mid-range (spans budget to premium)",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Palliative care",
      "Rehabilitation / Physiotherapy",
      "Nursing care",
    ],
    conditionCare: [
      "Dementia",
      "Parkinson's",
      "Stroke",
      "Coma",
      "Tracheostomy",
      "Cancer care",
    ],
    priceMin: 45000,
    priceMax: 60000,
    priceNote:
      "Basic package from ₹1,500/day; Premium package from ₹2,000/day (excluding medicines).",
    deposit: NA,
    amenities: [
      "Well-furnished rooms",
      "Nutritious daily meals",
      "Recreational activities",
      "Physiotherapy",
    ],
    staffRatio: "Team size ~70 members total",
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["General Indian meals"],
    dietary: ["Vegetarian (general)"],
    languages: [NA],
    licensing: [NA],
    rating: 4.9,
    reviewCount: 169,
    source: "eldercare.nears.me; impactguru.com",
    description:
      "A Vadodara care centre covering stroke, dementia, cancer and post-operative recovery with day-rate packages.",
  },
  {
    id: "dignity-foundation-mumbai",
    name: "Dignity Foundation",
    neighborhood: "Byculla East",
    city: "Mumbai",
    state: "Maharashtra",
    address:
      "B-206, 2nd Floor, Byculla Service Industries Premises, Dadoji Konddev Marg, Byculla (East), Mumbai 400027",
    phone: "022 6138 1100 · Helpline 1800 267 8780 (24/7)",
    email: "responsedignity@dignityfoundation.com",
    website: "dignityfoundation.com",
    tier: "NGO/Free care",
    tierLabel: "NGO (premium arm 'Dignity Lifestyle', Matheran)",
    careTypes: ["Day care", "Memory/dementia care", "Independent living", "Assisted living"],
    conditionCare: ["Dementia/Alzheimer's (core focus)", "Loneliness & elder-abuse support"],
    priceMin: 0,
    priceMax: 0,
    priceNote:
      "NGO core services largely free/subsidised; Dignity Lifestyle pricing not publicly listed.",
    deposit: NA,
    amenities: [
      "Physiotherapy",
      "Occupational therapy",
      "Yoga",
      "Nutritious meals",
      "Recreational activities",
      "Dignity Lifestyle: spa, pool, games area, library, prayer room, landscaped gardens",
    ],
    staffRatio: NA,
    hospitalTieUp: "Partnered with Bank of America for day-care programmes (CSR, not medical)",
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["Nutritious meals at day care centres"],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: ["Registered NGO, operating since 1995"],
    rating: 0,
    reviewCount: 0,
    source: "dignityfoundation.com; jeevinseniorcare.in",
    description:
      "A national elder-care NGO running geriatric and dementia day care centres, helplines and a premium Matheran community.",
  },
  {
    id: "sneha-sadan-vasai",
    name: "Sneha Sadan",
    neighborhood: "Vasai West",
    city: "Palghar",
    state: "Maharashtra",
    address: "Snehasadan Old Age Home, Vasai West, Palghar, Maharashtra",
    phone: "N/A direct (via samarth.community: 88001 83199)",
    email: "contact@samarthlife.org",
    tier: "NGO/Free care",
    tierLabel: "Budget/NGO",
    careTypes: ["Residential old-age home", "Assisted living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote:
      "Meryer's Home variant — refundable deposit ₹25,000 (3–4 sharing); general Vasai pricing N/A.",
    deposit: "₹25,000 refundable (Meryer's Home variant)",
    amenities: [NA],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 4.0,
    reviewCount: 18,
    source: "justdial.com; samarth.community",
    description: "A modest old-age residential home in Vasai West, Palghar district.",
  },
  {
    id: "gracias-living-gurgaon",
    name: "Gracias Living",
    neighborhood: "Sector 43",
    city: "Gurugram",
    state: "Delhi/NCR",
    address: "'Blossom' 901, Sector 43, Gurugram, Haryana 122009",
    website: "graciasliving.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Nursing care",
      "Palliative care",
      "Respite / short-stay",
    ],
    conditionCare: [
      "Dementia (dedicated programme, 24×7 supervision, structured routines)",
      "Post-stroke rehabilitation",
      "Post-hospital recovery",
      "Palliative care",
    ],
    priceMin: 66500,
    priceMax: 99500,
    priceNote:
      "Twin-sharing ₹66,500/month; single occupancy ₹99,500/month. Physiotherapy, medicines, medical tests, personal caregivers and electricity billed separately.",
    deposit: NA,
    amenities: [
      "5-minute ambulance response",
      "Daily vitals monitoring",
      "Personalized meal plans",
      "Housekeeping",
      "Hygiene protocols",
      "Activities & social events",
      "On-call doctor",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["Personalized meal plans; dietary preferences catered"],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "graciasliving.com; eldernest.info",
    description:
      "A Gurugram assisted-living residence with a dedicated dementia programme and 24×7 nursing.",
  },
  {
    id: "aurum-living-gurugram",
    name: "Aurum Senior & Assisted Living",
    neighborhood: "South City – 2",
    city: "Gurugram",
    state: "Delhi/NCR",
    address: "Block H1/10, South City – 2, Gurugram, Haryana 122008",
    website: "aurumliving.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: [
      "Independent living",
      "Assisted living",
      "Memory/dementia care",
      "Palliative care",
      "Nursing care",
    ],
    conditionCare: [
      "Alzheimer's/Dementia (programme led by Dr. Sonia Lal Gupta, US-trained Neurologist)",
      "Post-operative recovery",
      "General geriatric care",
    ],
    priceMin: 70000,
    priceMax: 180000,
    priceNote:
      "Rentals ₹70,000–₹1,80,000/month; extra caregivers billed per-hour / 8-hr / 12-hr / 24-hr separately.",
    deposit: NA,
    amenities: [
      "On-site emergency medical room",
      "24/7 ACLS-trained nurses",
      "Daily visiting house doctor",
      "Wheelchair-accessible & soundproof apartments",
      "Emergency call bells",
      "Anti-skid flooring",
      "Temperature-controlled AC & water",
      "Grab bars",
      "Micro-kitchens",
    ],
    staffRatio: NA,
    hospitalTieUp: "'Partnerships with leading hospitals' claimed, none named",
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["Diverse dining options"],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: ["N/A confirmed; founded and managed by a family of qualified physicians"],
    rating: 4.8,
    reviewCount: 0,
    source: "aurumliving.com; karocare.in",
    description:
      "A physician-run luxury senior residence in South City – 2 with a neurologist-led memory care programme.",
  },
  {
    id: "nirmal-hriday-kolkata",
    name: "Nirmal Hriday — Missionaries of Charity",
    neighborhood: "Kalighat",
    city: "Kolkata",
    state: "West Bengal",
    address: "251, Kalighat Road, Kolkata 700026",
    phone: "033-2464 4223",
    website: "missionariesofcharity.org",
    tier: "NGO/Free care",
    tierLabel: "NGO/Free",
    careTypes: ["Palliative care", "Residential old-age home"],
    conditionCare: [
      "Terminal illness",
      "Destitution and abandonment",
      "Palliative / end-of-life care",
    ],
    priceMin: 0,
    priceMax: 0,
    priceNote: "Free (donation-run)",
    deposit: NA,
    amenities: [
      "Basic shelter",
      "Food",
      "Medical attention",
      "Spiritual support from Missionary Sisters and volunteers",
    ],
    staffRatio: "N/A (run by nuns and volunteers)",
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["Basic meals (details not confirmed)"],
    dietary: ["No specific preference"],
    languages: ["Bengali", "English", "Hindi"],
    licensing: ["Missionaries of Charity (est. 1952); registered religious charitable trust"],
    rating: 0,
    reviewCount: 0,
    source: "missionariesofcharity.org; wanderlog.com",
    description:
      "The historic Kalighat hospice for the dying destitute, run free of charge by the Missionaries of Charity. Visiting hours Fri–Wed, closed Thursdays.",
  },
  {
    id: "helpage-india-delhi",
    name: "HelpAge India",
    neighborhood: "Qutab Institutional Area",
    city: "New Delhi",
    state: "Delhi/NCR",
    address: "C-14, Qutab Institutional Area, New Delhi 110016",
    phone: "+91-11-41688955/56 · Elder Helpline 1800-180-1253",
    email: "headoffice@helpageindia.org",
    website: "helpageindia.org",
    tier: "NGO/Free care",
    tierLabel: "NGO/Free",
    careTypes: ["Day care"],
    conditionCare: [
      "General elder welfare",
      "Healthcare access",
      "Legal aid for elder abuse",
      "Livelihood support",
    ],
    priceMin: 0,
    priceMax: 0,
    priceNote: "Free (donation-funded)",
    deposit: NA,
    amenities: ["Day care centres", "Mobile medical units", "Primary healthcare units"],
    staffRatio: NA,
    hospitalTieUp: "N/A named; runs its own mobile medical units",
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: ["Operates in 25 states — likely multilingual staff"],
    licensing: ["Registered NGO since 1978"],
    rating: 0,
    reviewCount: 0,
    source: "helpageindia.org; en.wikipedia.org",
    description:
      "Not a residential home — India's oldest elder-focused NGO, running 45 day care centres, self-help groups and mobile medical units.",
  },
  {
    id: "shibasram-trust-kolkata",
    name: "Shibasram Trust",
    neighborhood: "Santoshpur",
    city: "Kolkata",
    state: "West Bengal",
    address: "1250, P.G. Survey Park, Santoshpur, Kolkata, West Bengal 700075",
    phone: "+91 99038 14392",
    email: "shibasram@gmail.com",
    website: "shibasram.org.in",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Assisted living", "Memory/dementia care", "Nursing care"],
    conditionCare: ["Dementia/Alzheimer's (core specialisation)", "Bedridden patients"],
    priceMin: 0,
    priceMax: 0,
    priceNote:
      "N/A exact figures — 'affordable and transparent pricing with multiple care options'.",
    deposit: NA,
    amenities: [
      "Nutritious meals",
      "Medical personnel",
      "Health check-ups",
      "Medication management",
      "Doctor-on-call",
      "Ambulance service",
      "Yoga",
      "Spiritual gatherings",
      "Bengali cultural celebrations",
      "Shared & private rooms",
    ],
    staffRatio: NA,
    hospitalTieUp: "N/A named; near Kolkata's major hospitals on EM Bypass",
    distanceToHospital: "Near EM Bypass (exact km N/A)",
    distanceToAirport: NA,
    cuisine: ["Bengali cuisine emphasis", "Nutritious balanced meals"],
    dietary: ["Vegetarian (general)", "Non-Vegetarian available"],
    languages: ["Bengali"],
    licensing: ["Established 2013, registered Trust"],
    rating: 4.4,
    reviewCount: 206,
    source: "shibasram.org.in; justdial.com",
    description:
      "A Santoshpur assisted-living and dementia care home with Bengali cultural programming and doctor-on-call.",
  },
  {
    id: "antara-dehradun",
    name: "Antara Senior Living — Dehradun",
    neighborhood: "Purukul",
    city: "Dehradun",
    state: "Uttarakhand",
    address: "Antara Senior Living, Purukul, Dehradun, Uttarakhand (14-acre campus)",
    website: "antara-seniorliving.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: ["Independent living"],
    conditionCare: ["General age-related physical challenge accommodations"],
    priceMin: 33399,
    priceMax: 106213,
    priceNote:
      "Apartments variable; Antara Comprehensive Benefit (ACB) service package ₹33,399–₹1,06,213/month.",
    deposit: NA,
    amenities: [
      "Multiple dining spaces",
      "Golf putting greens",
      "Tennis & badminton courts",
      "Outdoor gym",
      "Bar",
      "Salon & spa",
      "Concierge",
      "Travel & legal assistance",
      "Grocery store",
      "Daily city shuttle",
      "Golf carts",
      "24/7 gated security",
      "CCTV",
      "Smoke & LPG detectors",
      "Emergency call buttons",
    ],
    staffRatio: NA,
    hospitalTieUp: "Max Super Specialty Hospital 'a short drive away'",
    distanceToHospital: "Short drive to Max Super Specialty Hospital",
    distanceToAirport: NA,
    cuisine: ["General dining options"],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: ["N/A confirmed; backed by Max India Group"],
    rating: 0,
    reviewCount: 0,
    source: "max-antara.co.in; jeevinseniorcare.in",
    description:
      "A 14-acre luxury independent living campus in the Mussoorie foothills with a full concierge service package.",
  },
  {
    id: "bethany-home-thiruvananthapuram",
    name: "Bethany Home for the Aged",
    neighborhood: "Bethel Gram, Kallayam",
    city: "Thiruvananthapuram",
    state: "Kerala",
    address:
      "Bethel Gram, Bethany for the Aged, CSI South Kerala Diocese, LMS Compound, Thiruvananthapuram, Kerala 695033",
    phone: "+91-471-2437901 / 2315781",
    tier: "NGO/Free care",
    tierLabel: "NGO/Free-to-low-cost",
    careTypes: ["Residential old-age home", "Assisted living"],
    conditionCare: ["General elder care"],
    priceMin: 0,
    priceMax: 0,
    priceNote: "N/A publicly disclosed",
    deposit: NA,
    amenities: ["N/A detailed — basic residential care (25 + 25 bed capacity)"],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["General Kerala / South Indian meals"],
    dietary: ["No specific preference"],
    languages: ["Malayalam"],
    licensing: ["Registered with Kerala state old-age home registry (2009, renewed through 2017)"],
    rating: 0,
    reviewCount: 0,
    source: "scribd.com; foscak.com",
    description:
      "A government-listed home for aged men and women run by the CSI South Kerala Diocese.",
  },
  {
    id: "lsp-mumbai-andheri",
    name: "Little Sisters of the Poor — Mumbai",
    neighborhood: "Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    address:
      "Opp Canossa Convent Primary School, Mahakali Caves Road, Gokul Nandanvan Co-op Society, Andheri East, Mumbai 400059",
    phone: "022-28364187",
    email: "lspmsmumbai@gmail.com",
    website: "littlesistersofthepoorindia.org",
    tier: "NGO/Free care",
    tierLabel: "NGO/Free",
    careTypes: ["Residential old-age home", "Assisted living"],
    conditionCare: ["General elder care for the destitute and abandoned"],
    priceMin: 0,
    priceMax: 0,
    priceNote: "Free",
    deposit: NA,
    amenities: [
      "TV",
      "Library",
      "Music",
      "Indoor games",
      "Local outings 4× a year",
      "General physician & specialist visits",
      "Wheelchair access",
      "Laundry by staff",
    ],
    staffRatio: "15 sisters serve 150 residents (~1 : 10)",
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["Vegetarian & Non-Vegetarian"],
    dietary: ["Vegetarian (general)", "Non-Vegetarian available", "Christian"],
    languages: [NA],
    licensing: ["International Catholic religious order, in India since 1882"],
    rating: 0,
    reviewCount: 0,
    source: "samarth.community; littlesistersofthepoorindia.in",
    description:
      "A free dormitory-style home in Andheri East for destitute elders, run by Catholic sisters.",
  },
  {
    id: "serene-urbana-bengaluru",
    name: "Serene Communities — Urbana",
    neighborhood: "Devanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Ozone Urbana Township, Devanahalli Taluk, Bengaluru 562110",
    phone: "Toll Free 1800 102 4010",
    website: "serenecommunities.in",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living", "Assisted living"],
    conditionCare: ["General wellness and assistance support"],
    priceMin: 0,
    priceMax: 0,
    priceNote:
      "1BHK–3BHK apartments; exact pricing not disclosed for Urbana (comparable Serene Pushkar Chennai units ₹40–45 Lakhs).",
    deposit: NA,
    amenities: [
      "Library",
      "Gym",
      "Community garden",
      "Swimming pool",
      "Housekeeping",
      "Laundry",
      "Maintenance",
      "Concierge",
      "24/7 security",
    ],
    staffRatio: NA,
    hospitalTieUp: "Proximity to 'established hospitals' claimed, none named",
    distanceToHospital: NA,
    distanceToAirport: "5 km from Kempegowda International Airport",
    cuisine: ["Vegetarian meals daily"],
    dietary: ["Vegetarian (general)"],
    languages: [NA],
    licensing: ["N/A confirmed; part of Columbia Pacific Communities"],
    rating: 0,
    reviewCount: 0,
    source: "serenecommunities.in",
    description:
      "A continuing-care retirement community inside Ozone Urbana, 5 km from Bengaluru airport.",
  },
  {
    id: "means-elders-care-hyderabad",
    name: "MEANS Elders Care",
    neighborhood: "Ramgopalpet",
    city: "Hyderabad",
    state: "Telangana",
    address: "No. 5-227, Krishna Nagar Colony, ECIL X Roads, Ramgopalpet, Hyderabad 500040",
    email: "meanshomes@gmail.com",
    website: "meansindia.org",
    tier: "NGO/Free care",
    tierLabel: "NGO / voluntary organisation",
    careTypes: ["Residential old-age home", "Assisted living"],
    conditionCare: ["General elder upliftment and healthcare"],
    priceMin: 0,
    priceMax: 0,
    priceNote: "N/A publicly disclosed",
    deposit: NA,
    amenities: ["Open 24 hours", "General elder care and upliftment services"],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: ["Registered voluntary organisation (Regn. No. 5671/1994)"],
    rating: 0,
    reviewCount: 0,
    source: "sulekha.com",
    description:
      "A Hyderabad voluntary organisation running an elder care home for poor and needy seniors.",
  },
  {
    id: "vedaanta-bangalore",
    name: "Vedaanta Senior Living — Bangalore",
    neighborhood: "Cunningham Road",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Suite No. 502, No.7, Prestige Center Point, Cunningham Road, Bengaluru, Karnataka",
    website: "vedaanta.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living", "Assisted living"],
    conditionCare: [
      "Regular health checkups",
      "Customized care plans",
      "Heart condition & diabetes-friendly meals",
    ],
    priceMin: 0,
    priceMax: 0,
    priceNote: "Bangalore projects from ₹60 Lakhs upward.",
    deposit: NA,
    amenities: [
      "Vegetarian meals daily with dietary customization",
      "24/7 healthcare services",
      "Regular checkups",
      "Community events & cultural programmes",
      "Group activities",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: ["Vegetarian meals with options for heart conditions and diabetes"],
    dietary: ["Vegetarian (general)"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "vedaanta.com",
    description:
      "Ownership-model retirement communities with 24/7 healthcare services and customised vegetarian dining.",
  },

  // ---- Athulya Senior Care branches ----
  {
    id: "athulya-kasavanahalli-bengaluru",
    name: "Athulya Senior Care — Kasavanahalli",
    neighborhood: "Kasavanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    address: "S.V. Towers, No 99/1, Kasavanahalli, Bengaluru, Karnataka 560100",
    website: "athulyaseniorcare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Transition care",
      "Rehabilitation / Physiotherapy",
      "Palliative care",
      "Home care",
    ],
    conditionCare: [NA],
    priceMin: 65000,
    priceMax: 85000,
    priceNote: "₹65,000–85,000/month",
    deposit: NA,
    amenities: ["130-bed facility near Electronic City"],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "athulyaseniorcare.com/location/kasavanahalli",
    description: "A 130-bed Athulya assisted living and memory care facility near Electronic City.",
  },
  {
    id: "athulya-whitefield-bengaluru",
    name: "Athulya Senior Care — Whitefield",
    neighborhood: "Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    address: "No. 28, R.Narayanapura, Whitefield, Bengaluru, Karnataka 560066",
    website: "athulyaseniorcare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Transition care",
      "Rehabilitation / Physiotherapy",
      "Palliative care",
      "Home care",
    ],
    conditionCare: [NA],
    priceMin: 65000,
    priceMax: 85000,
    priceNote: "₹65,000–85,000/month",
    deposit: NA,
    amenities: ["Newest Bengaluru facility"],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "athulyaseniorcare.com/bengaluru",
    description: "Athulya's newest Bengaluru assisted living and memory care residence.",
  },
  {
    id: "athulya-thudiyalur-coimbatore",
    name: "Athulya Senior Care — Thudiyalur",
    neighborhood: "Thudiyalur",
    city: "Coimbatore",
    state: "Tamil Nadu",
    address:
      "Mount Vue Apartment, VKL Nagar, Thudiyalur, Mettupalayam Road, Coimbatore 641042",
    website: "athulyaseniorcare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Transition care",
      "Rehabilitation / Physiotherapy",
      "Palliative care",
      "Home care",
    ],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: ["100-bed facility", "Coimbatore's largest assisted living facility"],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: "30 minutes from Coimbatore International Airport",
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "athulyaseniorcare.com/location/thudiyalur",
    description: "A 100-bed Athulya facility on Mettupalayam Road, Coimbatore's largest.",
  },
  {
    id: "athulya-kakkanad-kochi",
    name: "Athulya Senior Care — Kakkanad",
    neighborhood: "Kakkanad",
    city: "Kochi",
    state: "Kerala",
    address:
      "Tower 2, NRI Silicon Heights, NGO Quarters, Opp NPOL, Kunnampuram, Kakkanad, Kochi 682021",
    website: "athulyaseniorcare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Transition care",
      "Rehabilitation / Physiotherapy",
      "Palliative care",
      "Home care",
    ],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: ["70-bed facility", "Largest assisted living community in Kochi"],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "athulyaseniorcare.com/location/kochi",
    description: "A 70-bed Athulya assisted living community in Kakkanad, Kochi.",
  },
  {
    id: "athulya-kukatpally-hyderabad",
    name: "Athulya Senior Care — Kukatpally",
    neighborhood: "Kukatpally",
    city: "Hyderabad",
    state: "Telangana",
    address:
      "No. 615, Habeeb Nagar Road, Balanagar, Manal, Kukatpally, Hyderabad, Telangana 500072",
    website: "athulyaseniorcare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Transition care",
      "Rehabilitation / Physiotherapy",
      "Palliative care",
      "Home care",
    ],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: [NA],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "athulyaseniorcare.com/contact-us",
    description: "Athulya's Hyderabad assisted living and memory care branch in Kukatpally.",
  },

  // ---- Antara branches ----
  {
    id: "antara-noida",
    name: "Antara Senior Living — Noida",
    neighborhood: "Sector 150",
    city: "Noida",
    state: "Uttar Pradesh",
    address: "Plot No. SC-01/B-1, Sector 150, Noida, Uttar Pradesh 201310",
    website: "antaraseniorcare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: ["Independent living"],
    conditionCare: [NA],
    priceMin: 10000,
    priceMax: 113000,
    priceNote:
      "Apartments ₹1.09–1.52 Cr; Antara Comprehensive Benefit monthly fee ₹10,000–₹1,13,000/month.",
    deposit: NA,
    amenities: [
      "Panic alarm buttons",
      "Anti-skid tiles",
      "Wheelchair turning radius",
      "Round-the-clock medical assistance",
      "All-day restaurants",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "jllhomes.co.in; antaraseniorcare.com",
    description:
      "Antara's Noida independent living residences in Sector 150 with round-the-clock medical assistance.",
  },
  {
    id: "antara-gurugram",
    name: "Antara Senior Care — Gurugram",
    neighborhood: "DLF Phase 2",
    city: "Gurugram",
    state: "Delhi/NCR",
    address: "49, Gulmohar Marg, Opp. Airtel building, DLF Phase 2, Gurugram, Haryana 122010",
    website: "antaraseniorcare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: ["Assisted living", "Respite / short-stay", "Nursing care"],
    conditionCare: [NA],
    priceMin: 35000,
    priceMax: 150000,
    priceNote:
      "Basic facilities from ₹35,000/month; premium / long-term medical care homes from ₹1,50,000+/month.",
    deposit: NA,
    amenities: ["Customized care routines", "Health checkups", "Activities"],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "antaraseniorcare.com",
    description:
      "Antara's Gurugram care homes offering short-term and long-term assisted and medical care stays.",
  },

  // ---- CovaiCare branches ----
  {
    id: "covai-chinmayam-coimbatore",
    name: "CovaiCare — Covai Chinmayam",
    neighborhood: "Annur",
    city: "Coimbatore",
    state: "Tamil Nadu",
    address:
      "Nallur Vayal, Siruvani Main Road, Annur, Coimbatore; corporate office: CovaiCare Tower, Gem Nirmaalayam, VG Rao Nagar, Ganapathy, Coimbatore 641006",
    website: "covaicare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Mid-range",
    careTypes: ["Independent living", "Assisted living", "Memory/dementia care"],
    conditionCare: ["Dementia care", "PsWD (special needs adult) care"],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: [
      "80 independent villas (2BHK / 2.5BHK)",
      "6-acre eco-friendly community",
      "IGBC Green Homes rated (87/100)",
      "Pressalit Care (Denmark) bathroom fittings",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: "20-minute drive from Coimbatore city; 90 mins to Coonoor",
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 4.4,
    reviewCount: 49,
    source: "covaicare.com/covai-chinmayam-retirement-community",
    description:
      "An IGBC-rated 6-acre villa community near Coimbatore with assisted, dementia and special-needs care.",
  },
  {
    id: "covai-tapovan-solace-mysuru",
    name: "CovaiCare — Tapovan Solace",
    neighborhood: "Kuvempunagara",
    city: "Mysuru",
    state: "Karnataka",
    address: "19, JTK, 5th Phase, Kuvempu Nagar 2nd Stage, Kuvempunagara, Mysuru, Karnataka 570023",
    phone: "+91 821 248 8101",
    email: "rohan@tapovanprojects.com",
    website: "covaicare.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living", "Assisted living", "Palliative care"],
    conditionCare: [NA],
    priceMin: 22000,
    priceMax: 22000,
    priceNote: "Monthly packages start from ₹22,000.",
    deposit: NA,
    amenities: [
      "Clubhouse",
      "Swimming pool",
      "RFID access",
      "Modular kitchens",
      "Panic buttons",
      "Movement-sensor toilets",
      "Anti-skid flooring",
      "On-call doctors",
      "24/7 nurses & caregivers",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "eldercasa.com; goatsenior.com; covaicare.com",
    description:
      "A Mysuru senior living community with 24/7 nursing support and monthly packages from ₹22,000.",
  },

  // ---- Athashri branches ----
  {
    id: "athashri-bavdhan-pune",
    name: "Athashri Senior Living — Bavdhan (Aastha Pebbles)",
    neighborhood: "Bavdhan",
    city: "Pune",
    state: "Maharashtra",
    address:
      "Athashri Aastha Pebbles, Sr. No. 270/1/A/2, Behind Calsoft, Bavdhan Bk, Tal. Mulshi, Pune, Maharashtra",
    website: "pscl.in/athashri",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living", "Assisted living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: [
      "24×7 security",
      "CCTV",
      "Walking track",
      "Yoga & meditation spaces",
      "Art studio",
      "Guest rooms with housekeeping",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "pscl.in/athashri; facebook.com/aasthabyathashri",
    description:
      "Athashri's Bavdhan community in Pune, paired with the Aastha assisted-living arm.",
  },
  {
    id: "athashri-vadodara",
    name: "Athashri Senior Living — Vadodara",
    neighborhood: "Forest Trails",
    city: "Vadodara",
    state: "Gujarat",
    address:
      "Athashri Vadodara (Forest Trails project); corporate office: PSC House, Dr. Ketkar Road, Off Prabhat Road, Pune 411004",
    website: "pscl.in/projects/senior-living/athashri-vadodara",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: [
      "Non-skid floors",
      "Grab bars",
      "Panic switch alarms",
      "Generator-backed lifts",
      "24hr power",
      "Eco-friendly green living focus",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "pscl.in/projects/senior-living/athashri-vadodara",
    description: "Athashri's Vadodara independent living apartments in the Forest Trails project.",
  },

  // ---- Primus branches ----
  {
    id: "primus-ohana-bengaluru",
    name: "Primus Senior Living — Ohana",
    neighborhood: "Kudlu, South Bengaluru",
    city: "Bengaluru",
    state: "Karnataka",
    address: "South Bengaluru, near Hosa Lake and National Public School, Kudlu",
    website: "primuslife.in/bangalore/ohana",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: ["Independent living", "Assisted living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: [
      "Swimming pool",
      "Tennis court",
      "Forest walk",
      "Maze garden",
      "Library",
      "Gym",
      "In-house restaurant",
      "On-site medical centre",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "primuslife.in/bangalore/ohana",
    description: "A south Bengaluru Primus community with 1BHK residences and an on-site medical centre.",
  },
  {
    id: "primus-darpan-bengaluru",
    name: "Primus Senior Living — Darpan",
    neighborhood: "Kanakapura Road",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Kanakapura Road, Bengaluru (3 km from NICE Junction)",
    website: "primuslife.in/bangalore/darpan",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: ["Independent living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: "N/A — under construction, estimated possession March 2029.",
    deposit: NA,
    amenities: [
      "Emergency response systems",
      "Smart home solutions",
      "Temple space",
      "Game room",
      "Art gallery",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "primuslife.in/bangalore/darpan",
    description:
      "An upcoming Primus independent living project on Kanakapura Road (possession est. March 2029).",
  },
  {
    id: "primus-sangama-bengaluru",
    name: "Primus Senior Living — Sangama",
    neighborhood: "Kumbalagodu, Mysore Road",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Mysore Road, Kumbalagodu, South West Bengaluru",
    website: "homznspace.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: ["Independent living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: [
      "24×7 healthcare",
      "Concierge",
      "Housekeeping",
      "In-house restaurant",
      "Clubhouse",
      "Swimming pool",
      "Sports courts",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "homznspace.com/primus-sangama-senior-residences",
    description:
      "A multigenerational Primus community on Mysore Road with 1–3.5 BHK residences.",
  },
  {
    id: "primus-olympia-bengaluru",
    name: "Primus Senior Living — Olympia",
    neighborhood: "Kumbalgodu",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Gopalan Olympia township, Kumbalgodu, Bengaluru",
    website: "primuslife.in/bangalore/olympia",
    tier: "Premium/Medical care",
    tierLabel: "Premium/Luxury",
    careTypes: ["Independent living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: [
      "24/7 medical care",
      "On-campus clinic",
      "Nursing staff",
      "Physiotherapy",
      "Olympic-size pool",
      "Gym",
      "Multipurpose hall",
      "Concierge",
    ],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "primuslife.in/bangalore/olympia",
    description: "112 two-bedroom senior residences inside the Gopalan Olympia township.",
  },

  // ---- Vedaanta branches ----
  {
    id: "vedaanta-coimbatore",
    name: "Vedaanta Senior Living — Coimbatore",
    neighborhood: "Kovaiputhur",
    city: "Coimbatore",
    state: "Tamil Nadu",
    address:
      "Vedaanta Satsang, Sundakkamuthur Village Road, Kovaiputhur, Coimbatore 641010",
    website: "vedaanta.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living", "Assisted living", "Palliative care"],
    conditionCare: ["Post-operative care"],
    priceMin: 0,
    priceMax: 0,
    priceNote: "From ₹26 lakhs onwards.",
    deposit: NA,
    amenities: [NA],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["Vegetarian (general)"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "vedaanta.com/contact-vedaanta-senior-living.html",
    description:
      "Vedaanta Satsang in Coimbatore, offering independent and assisted living with palliative support.",
  },
  {
    id: "vedaanta-bellandur-bangalore",
    name: "Vedaanta Senior Living — Bellandur & HSR",
    neighborhood: "Bellandur / HSR Layout",
    city: "Bengaluru",
    state: "Karnataka",
    address:
      "No 78/9, Outer Ring Road, Bellandur Village, Varthur Hobli, Bengaluru 560103; also Hustle Hub 1901, 19th Main Road, HSR Layout, Bengaluru 560102",
    website: "vedaanta.com",
    tier: "Premium/Medical care",
    tierLabel: "Premium",
    careTypes: ["Independent living", "Assisted living"],
    conditionCare: [NA],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: [NA],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "vedaanta.com/contact-vedaanta-senior-living.html",
    description: "Vedaanta's additional Bengaluru offices and residences in Bellandur and HSR Layout.",
  },

  // ---- Dignity Foundation chapter ----
  {
    id: "dignity-foundation-chennai",
    name: "Dignity Foundation — Chennai Chapter",
    neighborhood: "Anna Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "No.F-27, old No.84, F Block, 2nd Street, Anna Nagar, Chennai 600102",
    phone: "044 3132 8562",
    email: "merita.joseph@dignityfoundation.com",
    website: "dignityfoundation.com",
    tier: "NGO/Free care",
    tierLabel: "NGO",
    careTypes: ["Day care", "Memory/dementia care"],
    conditionCare: ["Dementia day care"],
    priceMin: 0,
    priceMax: 0,
    priceNote: NA,
    deposit: NA,
    amenities: ["Dementia Day Care Centre", "Chai Masti Centres", "Helpline"],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["No specific preference"],
    languages: [NA],
    licensing: [NA],
    rating: 0,
    reviewCount: 0,
    source: "dignityfoundation.com/contact-us",
    description: "Dignity Foundation's Chennai chapter, running dementia day care and Chai Masti centres.",
  },

  // ---- Little Sisters of the Poor branches ----
  ...[
    {
      id: "lsp-bangalore-perpetual-secours",
      name: "Little Sisters of the Poor — Bangalore (Perpetual Secours)",
      neighborhood: "Hennur",
      city: "Bengaluru",
      state: "Karnataka",
      address: "Grace Town, 3rd Cross, Hennur Main Road, Bengaluru 560043",
      phone: "080-25444684",
      email: "lspmsbangps@gmail.com",
      source: "littlesistersofthepoorindia.in/contact-us.html",
    },
    {
      id: "lsp-bangalore-st-joseph",
      name: "Little Sisters of the Poor — Bangalore (St. Joseph)",
      neighborhood: "Richmond Town",
      city: "Bengaluru",
      state: "Karnataka",
      address: "26, Hosur Road, Richmond Town, Bengaluru 560025",
      phone: "080-22270273",
      email: "lspbangalorestjoseph@gmail.com",
      source: "littlesistersofthepoorindia.in/contact-us.html",
    },
    {
      id: "lsp-chennai",
      name: "Little Sisters of the Poor — Chennai",
      neighborhood: "Chetput",
      city: "Chennai",
      state: "Tamil Nadu",
      address: "11, Harrington Road, Chetput, Chennai 600031",
      phone: "044-28362963",
      email: "lspchn@bsnl.in",
      source: "littlesistersofthepoorindia.in/contact-us.html",
    },
    {
      id: "lsp-coonoor",
      name: "Little Sisters of the Poor — Coonoor",
      neighborhood: "Balaclava",
      city: "Coonoor",
      state: "Tamil Nadu",
      address: "Balaclava, P.O. Box No. 51, Coonoor 643102, Nilgiris District",
      phone: "0423-2206738",
      email: "lspmscoonoor@gmail.com",
      source: "littlesistersofthepoorindia.in/contact-us.html",
    },
    {
      id: "lsp-erode",
      name: "Little Sisters of the Poor — Erode",
      neighborhood: "Thindal",
      city: "Erode",
      state: "Tamil Nadu",
      address: "Perundurai Road, Thindal P.O., Erode District 638012",
      phone: "0423-2431138",
      email: "lsperode@gmail.com",
      source: "littlesistersofthepoorindia.in/contact-us.html",
    },
    {
      id: "lsp-guntur",
      name: "Little Sisters of the Poor — Guntur",
      neighborhood: "Nambur",
      city: "Guntur",
      state: "Andhra Pradesh",
      address: "Opp. Koppuravaru Road, Nambur 522508, Guntur District",
      phone: "0863-2293357",
      email: "lspmsguntur@gmail.com",
      source: "littlesistersofthepoorindia.in/contact-us.html",
    },
    {
      id: "lsp-jabalpur",
      name: "Little Sisters of the Poor — Jabalpur",
      neighborhood: "Rimjha",
      city: "Jabalpur",
      state: "Madhya Pradesh",
      address: "Katangi Road, St. Aloysius School Campus, Rimjha, Jabalpur 482002",
      phone: "0761-2688063",
      email: "lspmsjabalpur@gmail.com",
      source: "littlesistersofthepoorindia.in/contact-us.html",
    },
    {
      id: "lsp-secunderabad",
      name: "Little Sisters of the Poor — Secunderabad",
      neighborhood: "New Bhojguda",
      city: "Hyderabad",
      state: "Telangana",
      address: "6-1-33, New Bhojguda, Secunderabad, Hyderabad District 500003",
      email: "lspmssecbad@gmail.com",
      source: "littlesistersofthepoorindia.org/contact-littlesisters",
    },
    {
      id: "lsp-kolkata",
      name: "Little Sisters of the Poor — Kolkata",
      neighborhood: "Elgin",
      city: "Kolkata",
      state: "West Bengal",
      address: "2, Acharya Jagadish Chandra Bose Road, Elgin P.O., Kolkata 700020",
      phone: "033-2282 5552",
      email: "lspmskolkata@gmail.com",
      source: "lbb.in",
    },
    {
      id: "lsp-mysore",
      name: "Little Sisters of the Poor — Mysore",
      neighborhood: "Gandhinagar",
      city: "Mysuru",
      state: "Karnataka",
      address: "Mahadevapura Road, Gandhinagar, Mysore 570007",
      phone: "0821-2455017",
      email: "lspmsmysore@gmail.com",
      source: "littlesistersofthepoorindia.org/contact-littlesisters",
    },
    {
      id: "lsp-mangalore",
      name: "Little Sisters of the Poor — Mangalore",
      neighborhood: "Kulshekar",
      city: "Mangaluru",
      state: "Karnataka",
      address: "Kulshekar, Mangalore 575005",
      phone: "0824-2215269",
      email: "mangalorelsp@gmail.com",
      source: "littlesistersofthepoorindia.in; sulekha.com",
    },
    {
      id: "lsp-tuticorin",
      name: "Little Sisters of the Poor — Tuticorin",
      neighborhood: "Melur",
      city: "Tuticorin",
      state: "Tamil Nadu",
      address: "109/2D, Polenaickenpettai, Ettayapuram Road, Melur P.O., Tuticorin 628002",
      phone: "0461-2345453",
      email: "lspmstuty@gmail.com",
      amenities: [
        "Established 1973; current building completed 2012",
        "Accommodates 108 elderly residents",
        "Physiotherapy unit",
        "Occupational therapy unit",
      ],
      source: "littlesistersofthepoorindia.in/tuticorin",
    },
    {
      id: "lsp-sawantwadi",
      name: "Little Sisters of the Poor — Sawantwadi",
      neighborhood: "Nirwade",
      city: "Sawantwadi",
      state: "Maharashtra",
      address:
        "Behind Silver Acres Co-operative Housing Society Ltd., Nirwade, Sawantwadi 416510, Sindhudurg District",
      phone: "9152988358",
      email: "lspmssawantwadi@gmail.com",
      source: "littlesistersofthepoorindia.org/where-are-we",
    },
  ].map<RealFacilitySpec>((b) => ({
    id: b.id,
    name: b.name,
    neighborhood: b.neighborhood,
    city: b.city,
    state: b.state,
    address: b.address,
    phone: b.phone,
    email: b.email,
    website: "littlesistersofthepoorindia.org",
    tier: "NGO/Free care",
    tierLabel: "NGO/Free",
    careTypes: ["Residential old-age home", "Assisted living"],
    conditionCare: ["General elder care for the destitute and abandoned"],
    priceMin: 0,
    priceMax: 0,
    priceNote: "Free",
    deposit: NA,
    amenities: (b as { amenities?: string[] }).amenities ?? [NA],
    staffRatio: NA,
    hospitalTieUp: NA,
    distanceToHospital: NA,
    distanceToAirport: NA,
    cuisine: [NA],
    dietary: ["Christian", "No specific preference"],
    languages: [NA],
    licensing: ["International Catholic religious order, in India since 1882"],
    rating: 0,
    reviewCount: 0,
    source: b.source,
    description: `A free home for elderly people in need, run by the Little Sisters of the Poor in ${b.city}.`,
  })),
];
