// Real, publicly-sourced facility listings, rebuilt from the sourced research pass.
// All entries are UNVERIFIED until manually confirmed by the ElderMatch team.
// "N/A" is used verbatim wherever public information was unavailable — nothing is inferred.

export type SourceType = "official" | "secondary";
export type ListingKind = "residential" | "office" | "day-care";

export type RealFacilitySpec = {
  id: string;
  name: string;
  neighborhood: string;
  city: string;
  state: string;
  address: string;
  phone?: string;
  email?: string;
  website?: string;
  source: string;
  sourceType: SourceType;
  listingKind: ListingKind;
  listingNote?: string;
  tier: "NGO/Free care" | "Budget/Private" | "Mid-range assisted living" | "Premium/Medical care";
  tierLabel: string;
  careTypes: string[];
  conditionCare: string[];
  priceMin: number;
  priceMax: number;
  priceNote: string;
  deposit: string;
  itemizedCosts: { name: string; cost: string }[];
  amenities: string[];
  staffRatio: string;
  staffCredentials: string;
  medicalCapabilities: string[];
  hospitalTieUp: string;
  distanceToHospital: string;
  distanceToAirport: string;
  emergencyPlan: string;
  cuisine: string[];
  dietary: string[];
  languages: string[];
  licensing: string[];
  residentInterests: string[];
  trialStay: string;
  petFriendly: string;
  distantFamilySupport: string;
  yearFounded: string;
  rating: number;
  reviewCount: number;
  description: string;
  longDescription: string;
};

const NA = "N/A";

const ATHULYA_CARE = [
  "Assisted living",
  "Memory/dementia care",
  "Transition care",
  "Rehabilitation",
  "Palliative care",
];
const ATHULYA_CONDITIONS = [
  "Post-surgery recovery",
  "Dementia/Alzheimer's",
  "Palliative care",
  "Chronic illness (diabetes, hypertension)",
];

/** Shared defaults so every entry stays explicit about what is unknown. */
const base = {
  source: NA,
  sourceType: "official" as SourceType,
  listingKind: "residential" as ListingKind,
  priceMin: 0,
  priceMax: 0,
  priceNote: NA,
  deposit: NA,
  itemizedCosts: [] as { name: string; cost: string }[],
  amenities: [] as string[],
  staffRatio: NA,
  staffCredentials: NA,
  medicalCapabilities: [] as string[],
  hospitalTieUp: NA,
  distanceToHospital: NA,
  distanceToAirport: NA,
  emergencyPlan: NA,
  cuisine: [] as string[],
  dietary: [] as string[],
  languages: [] as string[],
  licensing: [] as string[],
  residentInterests: [] as string[],
  trialStay: NA,
  petFriendly: NA,
  distantFamilySupport: NA,
  yearFounded: NA,
  rating: 0,
  reviewCount: 0,
};

export const REAL_FACILITY_SPECS: RealFacilitySpec[] = [
  // ───────────────────────── KARNATAKA ─────────────────────────
  {
    ...base,
    id: "athulya-kasavanahalli-bengaluru",
    name: "Athulya Senior Care — Kasavanahalli",
    neighborhood: "Kasavanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Kasavanahalli, Bengaluru (full postal address N/A on site)",
    phone: "+91 98849 45900 (company-wide)",
    website: "athulyaseniorcare.com/location/kasavanahalli",
    source: "Official website",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Premium Assisted Living",
    careTypes: ATHULYA_CARE,
    conditionCare: ATHULYA_CONDITIONS,
    priceNote:
      "130 beds, largest Bengaluru facility, near Electronic City (official). Secondary sources (eldercasa.com, ketto.org) cite ₹65,000–₹85,000/mo for Athulya Bengaluru — not confirmed by the facility.",
    deposit: "₹10,000 one-time registration for single room (secondary: zenioro.com)",
    amenities: ["24/7 nursing", "Physical therapy on-site", "Leisure spaces", "Outdoor space"],
    staffCredentials:
      "Doctors, trained geriatric caregivers, nurses, physiotherapists, nutritionists (company-wide)",
    medicalCapabilities: ["24/7 nursing", "Physiotherapy", "Clinical supervision"],
    emergencyPlan: "On-call doctor available; ambulance and escalation protocol N/A",
    licensing: ['"Inspired by the standards of JCI and NABH" (company-wide — not a certification)'],
    yearFounded: "Athulya brand founded 2016",
    description:
      "130-bed premium assisted-living facility in Kasavanahalli near Electronic City.",
    longDescription:
      "Athulya's largest Bengaluru facility offering assisted living, mind & memory care, transition and palliative care under 24/7 clinical supervision.",
  },
  {
    ...base,
    id: "athulya-whitefield-bengaluru",
    name: "Athulya Senior Care — Whitefield",
    neighborhood: "Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Whitefield, Bengaluru (postal N/A)",
    phone: "+91 98849 45900 (company-wide)",
    website: "athulyaseniorcare.com/bengaluru",
    source: "Official website",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Premium Assisted Living",
    careTypes: ATHULYA_CARE,
    conditionCare: ATHULYA_CONDITIONS,
    priceNote:
      "Pricing N/A. Secondary source eldercasa.com cites ₹65,000–₹85,000/mo for Athulya Bengaluru.",
    amenities: ["24/7 nursing", "Physical therapy on-site", "Senior-friendly infrastructure"],
    staffCredentials:
      "Doctors, nurses, geriatric caregivers, physiotherapists, nutritionists (official)",
    medicalCapabilities: ["24/7 nursing", "Physiotherapy", "Rehabilitation"],
    emergencyPlan: "On-call doctor available",
    licensing: ["JCI/NABH-inspired standards (company-wide, not a certification)"],
    yearFounded: "Athulya brand founded 2016",
    description: "Athulya's Whitefield assisted-living branch in East Bengaluru.",
    longDescription:
      "One of two Athulya Bengaluru branches, offering assisted living and technology-oriented clinical care.",
  },
  {
    ...base,
    id: "athashri-whitefield-bengaluru",
    name: "Paranjape Athashri — Whitefield",
    neighborhood: "Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Athashri Road, Whitefield, Bengaluru",
    website: "pscl.in/athashri",
    source: "Official website + secondary (CommonFloor, Jeevin)",
    sourceType: "official",
    tier: "Mid-range assisted living",
    tierLabel: "Senior Living Community",
    careTypes: ["Independent living"],
    conditionCare: [],
    priceMin: 3500000,
    priceMax: 6500000,
    priceNote:
      "₹35 lakh (1 BHK) – ₹65 lakh (2 BHK) apartment purchase price, 785–1427 sqft on a 1.5-acre project (secondary: CommonFloor/Jeevin). Not a monthly care fee.",
    amenities: [
      "Club house",
      "Fitness centre",
      "Landscaped garden",
      "Library",
      "Lift",
      "24hr power backup",
      "Security",
    ],
    distanceToAirport: "Near Bengaluru International Airport (secondary)",
    licensing: ["RERA-registered"],
    yearFounded: "Athashri brand started 2002",
    description: "Paranjape Athashri senior-citizen apartment community in Whitefield.",
    longDescription:
      "1 & 2 BHK senior-living apartments on 1.5 acres near Bengaluru International Airport, part of the Athashri brand (2,500+ families across 15 communities per PR Newswire, Dec 2024).",
  },
  {
    ...base,
    id: "covaicare-urbana-irene-bengaluru",
    name: "CovaiCare — Urbana Irene",
    neighborhood: "Devanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Urbana Irene, Ozone Urbana Township, Kannamangala, Devanahalli, Bengaluru",
    website: "covaicare.com/urbana-irene-by-covai-bengaluru",
    source: "Official website",
    sourceType: "official",
    tier: "Mid-range assisted living",
    tierLabel: "Retirement Community",
    careTypes: ["Independent living", "Assisted living", "Memory/dementia care", "Palliative care"],
    conditionCare: ["Palliative care", "Dementia/Alzheimer's"],
    priceNote: "170 senior-friendly apartments (official). Pricing N/A.",
    amenities: [
      "Pressalit Care bathrooms (Denmark)",
      "Township amenities",
      "Commercial complex access",
      "Outdoor space",
    ],
    staffCredentials: "Team CovaiCare care staff",
    medicalCapabilities: ["20,000 sq ft Services & Care Facility", "Assisted care"],
    distanceToAirport: "6 km to Bengaluru International Airport (official)",
    yearFounded: "CovaiCare brand since 2004",
    description:
      "170-apartment senior community within Ozone Urbana township, 6 km from Bengaluru airport.",
    longDescription:
      "CovaiCare (pioneer of the 'Active life' senior-living concept since 2004) retirement community offering independent, assisted, memory and palliative care.",
  },
  {
    ...base,
    id: "covai-tapovan-solace-mysuru",
    name: "CovaiCare — Tapovan Solace",
    neighborhood: "Kuvempunagara",
    city: "Mysuru",
    state: "Karnataka",
    address: "Tapovan Solace, near Kuvempu Nagar, Mysuru",
    website: "covaicare.com/covai-tapovan-solace-retirement-community",
    source: "Official website + secondary (Jeevin)",
    sourceType: "official",
    tier: "Mid-range assisted living",
    tierLabel: "Retirement Community",
    careTypes: ["Independent living", "Assisted living", "Memory/dementia care", "Palliative care"],
    conditionCare: ["Palliative care", "Dementia/Alzheimer's"],
    priceNote: "1/2/3 BHK, IGBC Gold-rated building (official). Pricing N/A.",
    amenities: [
      "Clubhouse",
      "Swimming pool",
      "Library",
      "Video conferencing",
      "Walking tracks",
      "Grab bars",
      "Panic buttons",
    ],
    staffCredentials: "Nurses, caregivers, on-call doctors (secondary: Jeevin)",
    medicalCapabilities: [
      "24/7 medical assistance",
      "Physiotherapy",
      "Nutritionist on call",
      "In-house ambulance",
    ],
    hospitalTieUp:
      "Partnerships with leading hospitals for emergency hospitalisation (secondary: Jeevin)",
    emergencyPlan: "In-house ambulance (secondary)",
    cuisine: ["In-house cafeteria"],
    licensing: ["IGBC Gold rated"],
    distantFamilySupport: "Video conferencing facility (secondary)",
    description: "IGBC Gold-rated retirement community near Kuvempu Nagar, Mysuru.",
    longDescription:
      "CovaiCare–Tapovan joint retirement community with clubhouse, pool and 24/7 medical support.",
  },
  {
    ...base,
    id: "nightingales-medical-trust-bengaluru",
    name: "Nightingales Medical Trust (Centre for Ageing & Alzheimer's)",
    neighborhood: "Kasturi Nagar / RT Nagar",
    city: "Bengaluru",
    state: "Karnataka",
    address:
      "8P6, 3rd A Cross, Kasturinagar, Banaswadi, Bengaluru 560043 (RT Nagar centre: No. 337, 2nd Cross, 1st Block, RT Nagar 560032)",
    phone: "080-4242 6565 (24-hr)",
    email: "pro@nightingaleseldercare.com",
    website: "nightingaleseldercare.com",
    source: "Official website",
    sourceType: "official",
    tier: "NGO/Free care",
    tierLabel: "NGO Dementia Care",
    careTypes: [
      "Memory/dementia care",
      "Respite / short-stay",
      "Residential & day care",
      "Palliative care",
    ],
    conditionCare: [
      "Dementia/Alzheimer's",
      "Palliative care",
      "Chronic illness (Parkinson's, stroke)",
    ],
    priceNote:
      "Not-for-profit. One centre cited as 27–46% lower cost than market (official). Rupee figures N/A.",
    amenities: [
      "Open gardens",
      "Terraces",
      "Wide corridors with railings",
      "Elder-friendly bathrooms",
    ],
    staffCredentials:
      "Psychiatrists, psychologists, mental-health experts, occupational/speech/physio therapists (official)",
    medicalCapabilities: ["Memory clinic", "Telemedicine", "Physiotherapy", "Palliative care"],
    distanceToHospital: "Kasturi Nagar centre 6 km from MG Road; metro 2.5 km (official)",
    licensing: [
      "Registered not-for-profit trust, founded 1998 by Dr. Radha S. Murthy and S. Premkumar Raja",
    ],
    residentInterests: ["Active-ageing programmes"],
    yearFounded: "1998",
    description: "Bengaluru not-for-profit specialising in dementia and elder care since 1998.",
    longDescription:
      "Nightingales Medical Trust runs residential dementia care, memory clinics, day care and palliative services with affordable, telemedicine-supported care.",
  },
  {
    ...base,
    id: "primus-reflection-bengaluru",
    name: "Primus Senior Living — Reflection",
    neighborhood: "Kanakapura Road",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Kanakapura Main Road, opposite Art of Living Ashram, Bengaluru",
    website: "primuslife.in/bangalore/reflection",
    source: "Official website + secondary (karnataka.com)",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Senior Living",
    careTypes: ["Independent living"],
    conditionCare: [],
    priceNote: "163 ready-to-move apartments, 5 km from NICE Junction/metro (official). Pricing N/A.",
    amenities: ["Outdoor space", "Restaurants", "Wellness activities", "Housekeeping", "Dining"],
    medicalCapabilities: [
      "24×7 medical care",
      "Fall-preventive homes (anti-skid floors, grab bars, emergency buttons)",
    ],
    hospitalTieUp: "Top-tier hospitals nearby (secondary)",
    emergencyPlan: "Emergency call buttons in homes (official)",
    cuisine: ["Chef-prepared nutritious meals"],
    licensing: ["RERA-registered"],
    yearFounded: "Primus since 2013",
    description: "163-apartment luxury senior community on Kanakapura Road.",
    longDescription:
      "Primus Reflection offers fall-preventive senior apartments with 24×7 medical care, dining and wellness amenities.",
  },
  {
    ...base,
    id: "primus-ohana-bengaluru",
    name: "Primus Senior Living — Ohana",
    neighborhood: "Kudlu / Sarjapur",
    city: "Bengaluru",
    state: "Karnataka",
    address: "SJR Bluewaters, Harlur Main Road, Sarjapur, Bengaluru",
    website: "primuslife.in/bangalore/ohana",
    source: "Official website + secondary (PR Newswire)",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Senior Living",
    careTypes: ["Independent living"],
    conditionCare: [],
    priceNote: "1 & 3 BHK homes, 'nuclear joint family' concept. Pricing N/A.",
    amenities: [
      "Housekeeping",
      "Dining",
      "Healthcare support",
      "Nursing assistance",
      "Community engagement",
    ],
    medicalCapabilities: ["24×7 medical care", "Fall-preventive homes (company-wide)"],
    hospitalTieUp: "High-end specialty hospitals nearby (secondary)",
    emergencyPlan: "Emergency call buttons",
    cuisine: ["Chef-prepared meals"],
    licensing: ["RERA PRM/KA/RERA/1251/446/PR/200103/003096 (secondary: PR Newswire)"],
    yearFounded: "Primus since 2013",
    description: "Ready-to-move 1 BHK senior apartments in Sarjapur, Bengaluru.",
    longDescription:
      "Primus Ohana ('Ohana' = family) offers senior apartments in the SJR Bluewaters gated community with healthcare and hospitality services.",
  },
  {
    ...base,
    id: "primus-darpan-bengaluru",
    name: "Primus Senior Living — Darpan",
    neighborhood: "Kanakapura Road",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Kanakapura Road, ~3 km from NICE Junction, Bengaluru",
    website: "primuslife.in/bangalore/darpan",
    source: "Official website",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Senior Apartments",
    careTypes: ["Independent living"],
    conditionCare: [],
    priceNote: "1/2/2.5 BHK luxury apartments. Pricing N/A.",
    amenities: [
      "On-site medical centre",
      "Multipurpose hall",
      "In-house restaurant",
      "Senior-friendly swimming pool",
      "Temple space",
    ],
    medicalCapabilities: ["On-site medical centre", "24×7 medical care", "Fall-preventive homes"],
    hospitalTieUp: "St. John's Medical College Hospital at Brigade Meadows, ~500 m away (official)",
    distanceToHospital: "500 m",
    emergencyPlan: "On-site medical centre",
    cuisine: ["In-house restaurant"],
    licensing: ["RERA-registered"],
    residentInterests: ["Cultural programmes"],
    yearFounded: "Primus since 2013",
    description:
      "Luxury 1/2/2.5 BHK senior apartments on Kanakapura Road with an on-site medical centre.",
    longDescription:
      "Primus Darpan offers hospitality-driven luxury senior living with pool, restaurant, temple space and St. John's Hospital 500 m away.",
  },
  {
    ...base,
    id: "primus-sangama-bengaluru",
    name: "Primus Senior Living — Sangama",
    neighborhood: "Mysore Road",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Mysore Road, Bengaluru (postal N/A)",
    website: "primuslife.in/bangalore",
    source: "Official website (company-wide detail only)",
    sourceType: "official",
    listingNote: "Branch-specific webpage detail is thin; most details are company-wide.",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Senior Living",
    careTypes: ["Independent living"],
    conditionCare: [],
    amenities: ["Housekeeping", "Dining", "Recreation", "Wellness"],
    medicalCapabilities: ["24×7 medical care", "Fall-preventive homes (company-wide)"],
    emergencyPlan: "Emergency buttons (company-wide)",
    yearFounded: "Primus since 2013",
    description: "Primus senior living community on Mysore Road, Bengaluru.",
    longDescription:
      "One of Primus's Bengaluru senior communities offering age-friendly homes with hospitality and wellness services.",
  },
  {
    ...base,
    id: "primus-olympia-bengaluru",
    name: "Primus Senior Living — Olympia",
    neighborhood: "Kumbalgodu",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Kumbalgodu, Bengaluru (postal N/A)",
    website: "primuslife.in/bangalore",
    source: "Official website (company-wide detail only)",
    sourceType: "official",
    listingNote: "Branch-specific data is thin; most details are company-wide.",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Senior Living",
    careTypes: ["Independent living"],
    conditionCare: [],
    amenities: ["Housekeeping", "Dining", "Recreation", "Wellness"],
    medicalCapabilities: ["24×7 medical care", "Fall-preventive homes (company-wide)"],
    emergencyPlan: "Emergency buttons (company-wide)",
    yearFounded: "Primus since 2013",
    description: "Primus senior living community at Kumbalgodu, Bengaluru.",
    longDescription:
      "A Primus Bengaluru senior community offering residences with age-friendly design and professional care.",
  },
  {
    ...base,
    id: "ashley-care-homes-bengaluru",
    name: "Ashley Care Homes",
    neighborhood: "Horamavu / Kalkere",
    city: "Bengaluru",
    state: "Karnataka",
    address:
      "M.R. Complex, 387/1, 2nd Floor, Kalkere–Horamavu Main Road, Rajkumar Layout, Kalkere, Horamavu Post, Bengaluru 560043",
    phone: "9880763745 / 9731617730",
    email: "ashleycarehomes@gmail.com",
    website: "ashleycarehomes.in",
    source: "Official website + secondary (Sulekha, ReachOutIndia)",
    sourceType: "official",
    tier: "Budget/Private",
    tierLabel: "Private Care Home",
    careTypes: [
      "Assisted living",
      "Nursing care",
      "Palliative care",
      "Geriatric care",
      "Post-operative care",
    ],
    conditionCare: [
      "Post-surgery recovery",
      "Bedridden care",
      "Palliative care",
      "Chronic illness (diabetes, hypertension)",
    ],
    staffCredentials: "Visiting GP, on-call doctors, nursing staff (official)",
    medicalCapabilities: [
      "24-hr nursing",
      "Medication management",
      "Physiotherapy",
      "Palliative care",
    ],
    emergencyPlan: "On-call doctors (official)",
    trialStay: "Short-term stays available (official); terms and pricing N/A",
    yearFounded: "2009 (secondary: Sulekha)",
    description:
      "Family-run private assisted-living and nursing care home in Horamavu, Bengaluru (est. 2009).",
    longDescription:
      "Ashley Care Homes, run by Anthony & Cynthia Cunliffe, offers assisted living, 24-hr nursing, physiotherapy and palliative care with short and long-term stays.",
  },
  {
    ...base,
    id: "serene-urbana-bengaluru",
    name: "Serene Urbana by Columbia Pacific Communities",
    neighborhood: "Devanahalli",
    city: "Bengaluru",
    state: "Karnataka",
    address:
      "Ozone Urbana integrated township, Devanahalli, North Bengaluru (corporate: 2999, 12th A Main Rd, HAL 2nd Stage, Indiranagar, Bengaluru 560008)",
    phone: "+91-8884555554 (WhatsApp +91-8000094944)",
    email: "sales@columbiacommunities.in",
    website: "serenecommunities.in/senior-living/bangalore/serene-urbana",
    source: "Official website",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Continuing-Care Senior Living",
    careTypes: ["Independent living", "Assisted living", "Continuing care"],
    conditionCare: [],
    priceMin: 3000000,
    priceMax: 10000000,
    priceNote:
      "₹30 lakh (1 BHK) – ₹1 crore (3 BHK) apartment purchase (official); monthly service charge billed separately. Secondary (Jeevin) cites monthly rental packages from ₹28,000.",
    itemizedCosts: [{ name: "Monthly service charge", cost: "Billed separately — amount N/A" }],
    amenities: ["Community amenities", "'Life at Serene' facilities"],
    staffCredentials: "Medical & paramedical staff trained by Columbia Asia Hospitals (official)",
    medicalCapabilities: ["Periodic wellness checkups", "24×7 ambulance", "Emergency protocols"],
    hospitalTieUp: "Staff trained by Columbia Asia Hospitals (official)",
    distanceToAirport: "~5 km to Kempegowda International Airport (official)",
    emergencyPlan: "24×7 ambulance and on-call emergency response (official)",
    cuisine: ["Meals included in service package"],
    licensing: [
      "RERA (sister project Serene Amara PRM/KA/RERA/1251/309/PR/160223/005724 — not Urbana specifically)",
    ],
    description:
      "Premium continuing-care senior living community within Ozone Urbana, 5 km from Bengaluru airport.",
    longDescription:
      "Serene Urbana by Columbia Pacific offers 1–3 BHK senior apartments (₹30L–₹1 cr) with continuing care, wellness checkups and Columbia Asia-trained staff.",
  },
  {
    ...base,
    id: "vedaanta-bangalore",
    name: "Vedaanta Senior Living — Cunningham Road office",
    neighborhood: "Cunningham Road",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Suite 502, No.7, Prestige Center Point, Cunningham Road, Bengaluru",
    website: "vedaanta.com/contact-vedaanta-senior-living.html",
    source: "Official website (contact page)",
    sourceType: "official",
    listingKind: "office",
    listingNote: "This address is an office suite, not a care facility.",
    tier: "Premium/Medical care",
    tierLabel: "Senior Living Developer (office)",
    careTypes: ["Independent living"],
    conditionCare: [],
    priceNote: "Not applicable — corporate/sales office.",
    staffCredentials: "Management team with ~100 years of combined senior-living experience",
    description: "Vedaanta Senior Living's Bengaluru office at Cunningham Road.",
    longDescription:
      "Corporate/enquiry office of Vedaanta Senior Living, a retirement-community developer; not a standalone residential care home at this address.",
  },
  {
    ...base,
    id: "vedaanta-bellandur-bangalore",
    name: "Vedaanta Senior Living — Bellandur / HSR Layout",
    neighborhood: "Bellandur / HSR Layout",
    city: "Bengaluru",
    state: "Karnataka",
    address:
      "No 78/9, Outer Ring Road, Bellandur Village, Varthur Hobli, Bengaluru 560103 (also HSR: Hustle Hub, 1901 19th Main Rd, HSR Layout 560102)",
    website: "vedaanta.com/contact-vedaanta-senior-living.html",
    source: "Official website (contact page)",
    sourceType: "official",
    listingKind: "office",
    listingNote: "These are office addresses, not operational care facilities.",
    tier: "Premium/Medical care",
    tierLabel: "Senior Living Developer office",
    careTypes: ["Independent living"],
    conditionCare: [],
    priceNote: "Not applicable — office address.",
    description: "Vedaanta Senior Living Bengaluru offices (Bellandur & HSR Layout).",
    longDescription:
      "Vedaanta's Bengaluru presence is via office addresses; its Bengaluru residential concept is the Vedaanta Anugraham integrated township.",
  },

  // ───────────────────────── TAMIL NADU ─────────────────────────
  {
    ...base,
    id: "athulya-pallavaram-chennai",
    name: "Athulya Senior Care — Pallavaram",
    neighborhood: "Pallavaram",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "Pallavaram, Chennai (minutes from Chennai International Airport; full postal N/A)",
    phone: "+91 98849 45900 (company-wide)",
    website: "athulyaseniorcare.com/chennai",
    source: "Official website",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Premium Assisted Living (flagship)",
    careTypes: ATHULYA_CARE,
    conditionCare: ATHULYA_CONDITIONS,
    priceNote:
      "120-bed flagship, 'one of India's largest Assisted Living facilities' (official about-us). Pricing N/A.",
    amenities: ["Top-tier amenities", "'Home Away from Home' design"],
    staffCredentials:
      "Doctors, nurses, physiotherapists, nutritionists, caregivers (official)",
    medicalCapabilities: ["24/7 clinical supervision"],
    distanceToAirport: "Minutes from Chennai International Airport (official)",
    emergencyPlan: "On-call doctor",
    licensing: ["JCI/NABH-inspired standards (company-wide, not a certification)"],
    distantFamilySupport: "Explicitly designed for families living afar (official)",
    yearFounded: "Athulya brand founded 2016",
    description: "Athulya's 120-bed flagship assisted-living facility near Chennai airport.",
    longDescription:
      "Athulya Pallavaram, one of India's largest assisted-living facilities, offers clinical supervision and premium amenities designed for families living far away.",
  },
  {
    ...base,
    id: "athulya-thudiyalur-coimbatore",
    name: "Athulya Senior Care — Thudiyalur",
    neighborhood: "Thudiyalur",
    city: "Coimbatore",
    state: "Tamil Nadu",
    address: "Thudiyalur, Coimbatore (postal N/A)",
    phone: "+91 98849 45900 (company-wide)",
    website: "athulyaseniorcare.com/location/coimbatore",
    source: "Official website (company-wide detail only)",
    sourceType: "official",
    listingNote: "Branch-specific page detail is thin.",
    tier: "Premium/Medical care",
    tierLabel: "Premium Assisted Living",
    careTypes: ATHULYA_CARE,
    conditionCare: ATHULYA_CONDITIONS,
    amenities: ["Senior-friendly infrastructure (company-wide)"],
    medicalCapabilities: ["24/7 nursing", "Physiotherapy"],
    licensing: ["JCI/NABH-inspired standards (company-wide, not a certification)"],
    yearFounded: "Athulya brand founded 2016",
    description: "Athulya assisted-living facility in Thudiyalur, Coimbatore.",
    longDescription:
      "Athulya's Coimbatore branch offering assisted living, memory care, rehabilitation and palliative care.",
  },
  {
    ...base,
    id: "ashiana-shubham-chennai",
    name: "Ashiana Shubham",
    neighborhood: "Maraimalai Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "Maraimalai Nagar, GST Road, Chennai (20-acre gated community)",
    website: "ashianahousing.com/senior-living-india/chennai",
    source: "Official website + secondary (RoofandFloor, 99acres)",
    sourceType: "official",
    tier: "Mid-range assisted living",
    tierLabel: "Active Senior Living",
    careTypes: ["Independent living"],
    conditionCare: [],
    priceMin: 3979000,
    priceMax: 6693000,
    priceNote:
      "₹39.79 lakh – ₹66.93 lakh apartment purchase (Phase 4, RERA TN/01/Building/0456/2020; ~220 units on 2 acres, 865–1455 sq ft, ~₹4,600/sq ft — secondary: RoofandFloor/99acres).",
    itemizedCosts: [{ name: "Café meal", cost: "₹170 + GST (official)" }],
    amenities: [
      "34,000 sq ft clubhouse",
      "Swimming pool",
      "Walking tracks",
      "Worship hall",
      "Lawn tennis",
      "Board games",
      "Vegetarian café",
    ],
    medicalCapabilities: ["Senior-friendly, wheelchair accessible design"],
    emergencyPlan: "24/7 security & CCTV (official)",
    cuisine: ["Satvik vegetarian café meals"],
    dietary: ["Vegetarian (general)"],
    licensing: ["RERA TN/01/Building/0456/2020"],
    residentInterests: ["Board games", "Tennis"],
    yearFounded: "Phase 1 operational (~40 families)",
    description:
      "20-acre active senior living community in Maraimalai Nagar with a 34,000 sq ft clubhouse.",
    longDescription:
      "Ashiana Shubham offers 1–3 BHK senior-friendly residences with clubhouse, pool, vegetarian café and 24/7 security.",
  },
  {
    ...base,
    id: "anandam-community-chennai",
    name: "Anandam — A Free Home for Senior Citizens (Anandam Trust)",
    neighborhood: "Kallikuppam, Ambattur",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "Anna Street, Gangai Nagar, Kallikuppam, Ambattur, Chennai 600053",
    phone: "044-26860099 (admissions: K. Narayanan 9841001925)",
    email: "anandamtrust2003@gmail.com",
    website: "anandamoldagehome.org",
    source: "Official website",
    sourceType: "official",
    tier: "NGO/Free care",
    tierLabel: "Free Home for Elders",
    careTypes: ["Residential elder care (destitute seniors)", "Assisted living"],
    conditionCare: ["Chronic illness (diabetes, hypertension)", "Bedridden care"],
    priceNote: "Free home funded by donors; sponsor-an-elder option available.",
    deposit: "None",
    amenities: [
      "24,000 sq ft two-storey facility",
      "Beds with attached bath/toilet",
      "Meals provided",
    ],
    staffCredentials: "Voluntary doctors and caregivers (official)",
    medicalCapabilities: ["Medical care", "Hospital-supported services"],
    hospitalTieUp:
      "Sri Ramachandra Hospital, Meenakshi Ammal Dental College, Aravind Eye Hospital, Dr. Rangarajan Memorial Hospital, Astra Hearing Care (official)",
    emergencyPlan: "Hospital tie-ups for emergencies (official)",
    cuisine: ["Meals provided"],
    dietary: ["Vegetarian (general)"],
    languages: ["Tamil"],
    licensing: ["Anandam Trust (est. 1995)"],
    yearFounded: "Home 2003, trust 1995 (official)",
    description:
      "Free charitable home in Ambattur for destitute seniors over 60 with no children or income.",
    longDescription:
      "Anandam (est. 2003 by Anandam Trust) provides free shelter, meals and medical care to ~110 destitute elders in a purpose-built Ambattur facility, supported by leading Chennai hospitals.",
  },
  {
    ...base,
    id: "covai-chinmayam-coimbatore",
    name: "CovaiCare — Covai Chinmayam",
    neighborhood: "Annur",
    city: "Coimbatore",
    state: "Tamil Nadu",
    address: "Annur, Coimbatore (near the Nilgiris, ~90 min to Coonoor)",
    website: "covaicare.com/covai-chinmayam-senior-living",
    source: "Official website",
    sourceType: "official",
    tier: "Mid-range assisted living",
    tierLabel: "Retirement Community",
    careTypes: [
      "Independent living",
      "Assisted living",
      "Memory/dementia care",
      "Persons-with-disability care",
    ],
    conditionCare: ["Dementia/Alzheimer's"],
    priceNote: "6-acre villa community, IGBC 87/100 green rating (official). Pricing N/A.",
    amenities: [
      "Pressalit Care wheelchair-friendly bathrooms (Denmark)",
      "Vocational centre",
      "Green environment",
      "Outdoor space",
    ],
    staffCredentials: "Team CovaiCare",
    medicalCapabilities: ["Assisted care", "Dementia care", "Persons-with-disability care"],
    licensing: ["IGBC Green Homes, 87 points"],
    description: "6-acre eco-friendly retirement villa community in Annur, Coimbatore.",
    longDescription:
      "Covai Chinmayam offers senior villas with assisted, dementia and persons-with-disability care, IGBC-rated 87/100.",
  },
  {
    ...base,
    id: "vedaanta-coimbatore",
    name: "Vedaanta Satsang — Kovaipudur",
    neighborhood: "Kovaipudur",
    city: "Coimbatore",
    state: "Tamil Nadu",
    address: "Vedaanta Satsang, Sundakkamuthur Village Road, Kovaiputhur, Coimbatore 641010",
    website: "vedaanta.com/vedaanta-satsang-coimbatore",
    source: "Official website",
    sourceType: "official",
    tier: "Mid-range assisted living",
    tierLabel: "Retirement Community",
    careTypes: ["Independent living", "Paramedical support"],
    conditionCare: [],
    priceMin: 3500000,
    priceNote:
      "Apartments from ~₹35 lakh (secondary: JLL); independent villas sold out (Oct 2021 handover). Upper range N/A.",
    amenities: [
      "Common vegetarian kitchen and dining",
      "Community hall",
      "Geriatric gym",
      "Gardens",
      "Prayer halls",
      "Walking tracks",
      "Buggy service",
      "Video conferencing",
    ],
    staffCredentials: "Nurses and paramedical staff (official)",
    medicalCapabilities: [
      "24×7 paramedical resources",
      "Medical centre / clinic",
      "Ambulance service",
    ],
    emergencyPlan: "In-house ambulance (official)",
    cuisine: ["Vegetarian common dining"],
    dietary: ["Vegetarian (general)"],
    licensing: ["DTCP approved"],
    distantFamilySupport: "Video conferencing (official)",
    yearFounded: "Services began Oct 2021 (official)",
    description:
      "Retirement community near Kovaipudur ('Mini-Ooty'), Coimbatore, operational since Oct 2021.",
    longDescription:
      "Vedaanta Satsang offers senior villas and apartments with vegetarian dining, 24×7 paramedical care, a geriatric gym and ambulance service.",
  },
  {
    ...base,
    id: "dignity-foundation-chennai",
    name: "Dignity Foundation — Chennai Chapter",
    neighborhood: "Anna Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    address:
      "No. F-27 (old No. F-84), F Block, Ground Floor, 2nd Street, Anna Nagar East, Chennai 600102",
    phone: "+91 98403 95943 / 044 3132 8562",
    email: "felista.jose@dignityfoundation.com",
    website: "dignityfoundation.com",
    source: "Official website",
    sourceType: "official",
    listingKind: "day-care",
    listingNote: "Day-care / programme chapter, not a residential old-age home.",
    tier: "NGO/Free care",
    tierLabel: "NGO Senior Services",
    careTypes: ["Dementia day care", "Active-ageing programmes"],
    conditionCare: ["Dementia/Alzheimer's"],
    priceNote: "Membership-based non-profit; figures N/A.",
    staffCredentials: "Trained caregivers and therapists (official)",
    medicalCapabilities: ["Physiotherapy", "Occupational therapy", "Yoga at dementia day care"],
    licensing: ["Registered non-profit, founded 1995 by Dr. Sheilu Sreenivasan"],
    yearFounded: "1995 (organisation)",
    description: "Chennai chapter of Dignity Foundation offering dementia day care and senior programmes.",
    longDescription:
      "Dignity Foundation (est. 1995) runs a dementia day-care centre and senior support programmes in Anna Nagar; primarily day services, not residential care.",
  },

  // ───────────────────────── DELHI / NCR ─────────────────────────
  {
    ...base,
    id: "gracias-living-gurgaon",
    name: "Gracias Living",
    neighborhood: "Sector 43",
    city: "Gurugram",
    state: "Haryana",
    address: "'Blossom' 901, Sector 43, Gurugram 122009 (2nd address: 'Zinnia' S27/6, DLF Phase 3)",
    phone: "+91 87004 84949",
    email: "contact@graciasliving.com",
    website: "graciasliving.com",
    source: "Official website",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Assisted Living & Memory Care",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Post-operative / rehabilitation",
      "Palliative / geriatric care",
      "Respite / short-stay",
    ],
    conditionCare: [
      "Post-surgery recovery",
      "Dementia/Alzheimer's",
      "Palliative care",
      "Paralysis",
      "Bedridden care",
    ],
    amenities: [
      "Secure private rooms",
      "Physical therapy on-site",
      "Recreational & cognitive engagement",
      "Housekeeping",
      "Wi-Fi",
      "Pet-friendly",
      "Transportation",
    ],
    staffCredentials: "Doctors and nursing staff; founder Meenakshi (official)",
    medicalCapabilities: [
      "24/7 medical supervision",
      "Physiotherapy",
      "Nutrition planning",
      "5-minute ambulance service",
    ],
    emergencyPlan: "5-minute ambulance service and emergency support (official)",
    cuisine: ["Special dietary accommodations"],
    trialStay: "Respite / short-term stays available (official); terms N/A",
    petFriendly: "Yes (aggregator listing)",
    description: "Luxury assisted-living and memory-care home in Sector 43, Gurugram.",
    longDescription:
      "Gracias Living provides 24/7 medical care, dementia/memory care, post-operative recovery, physiotherapy and palliative support in a home-like Gurugram setting.",
  },
  {
    ...base,
    id: "aurum-living-gurugram",
    name: "Aurum Senior & Assisted Living",
    neighborhood: "South City-2",
    city: "Gurugram",
    state: "Haryana",
    address: "Block H1/10, South City-2, Gurugram, Haryana 122008",
    phone: "+91 98108 09965",
    email: "contactus@aurumliving.com",
    website: "aurumliving.com",
    source: "Official website",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Senior & Assisted Living",
    careTypes: [
      "Independent living",
      "Assisted living",
      "Memory/dementia care",
      "Post-operative recovery",
      "Geriatric care",
      "Palliative care",
    ],
    conditionCare: [
      "Post-surgery recovery",
      "Dementia/Alzheimer's",
      "Palliative care",
      "Chronic illness (diabetes, hypertension)",
    ],
    priceNote: "Rentable suites and studio apartments across 40,000 sq ft (official). Pricing N/A.",
    itemizedCosts: [
      { name: "Deluxe Suite", cost: "N/A" },
      { name: "Junior Suite", cost: "N/A" },
      { name: "Park-view Apartment", cost: "N/A" },
      { name: "Deluxe Studio", cost: "N/A" },
    ],
    amenities: [
      "Studio apartments and suites with balconies",
      "Park views",
      "Safety fixtures",
      "6 meals per day",
      "Housekeeping",
      "Concierge",
    ],
    staffRatio: "24-hour staffing coverage (official); resident-to-staff ratio N/A",
    staffCredentials:
      "Founded by medical practitioners; dementia care led by Dr. Sonia Lal Gupta, US-trained neurologist (official)",
    medicalCapabilities: ["Clinical oversight", "Emergency response", "24/7 care"],
    emergencyPlan: "Emergency response capability (official)",
    cuisine: ["Home-cooked meals, 6× daily"],
    residentInterests: ["Happiness Manager activities", "Clinical psychologist-led sessions"],
    yearFounded: "Built 2019–2020, opened Dec 2020 (official)",
    description:
      "Doctor-founded luxury senior & assisted living residence (opened Dec 2020) in South City-2, Gurugram.",
    longDescription:
      "Aurum offers rentable suites and studios across 40,000 sq ft with 24-hour staffing, US-trained neurologist-led dementia care, six daily meals and concierge services.",
  },
  {
    ...base,
    id: "antara-gurugram",
    name: "Antara Care Homes — DLF Phase 2",
    neighborhood: "DLF Phase 2",
    city: "Gurugram",
    state: "Haryana",
    address:
      "No. 49, Gulmohar Marg, opp. Airtel building, Mushedpur, Sector 25, DLF Phase 2, Gurugram 122002",
    website: "old-age-homes.antaraseniorcare.com/care-homes/gurugram/dlf-phase-2",
    source: "Official website",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Transition & Assisted Care Home",
    careTypes: [
      "Assisted living",
      "Transition / post-operative care",
      "Rehabilitation",
      "Palliative care",
      "Memory/dementia care",
    ],
    conditionCare: [
      "Post-surgery recovery",
      "Paralysis",
      "Palliative care",
      "Dementia/Alzheimer's",
    ],
    priceNote: "83-room property with single and double occupancy (official). Pricing N/A.",
    amenities: ["Nutritionally assisted meals", "Engagement calendars", "Curated care plans"],
    staffCredentials: "Doctors, nurses and therapists (official)",
    medicalCapabilities: [
      "24×7 nursing",
      "Doctor supervision",
      "Physiotherapy",
      "Personalised care plans",
    ],
    emergencyPlan: "Primary health care and emergency response (official)",
    cuisine: ["Nutritionally assisted meals"],
    licensing: ["Max Group / Antara"],
    trialStay: "Short-term care available (official); terms N/A",
    yearFounded: "Antara founded 2011",
    description:
      "Antara transition & assisted care home in DLF Phase 2, Gurugram for post-operative and rehab recovery.",
    longDescription:
      "Antara Care Homes (Max Group) provide assisted living, stroke/paralysis rehab, post-surgery recovery and palliative care with 24×7 nursing and doctor supervision.",
  },
  {
    ...base,
    id: "helpage-india-delhi",
    name: "HelpAge India (Head Office)",
    neighborhood: "Qutab Institutional Area",
    city: "New Delhi",
    state: "Delhi",
    address: "C-14, Qutab Institutional Area, New Delhi 110016",
    phone: "+91-11-41688955 / 56",
    email: "headoffice@helpageindia.org",
    website: "helpageindia.org",
    source: "Official website + Wikipedia",
    sourceType: "official",
    listingKind: "office",
    listingNote: "Head office / administrative address, not a residential old-age home.",
    tier: "NGO/Free care",
    tierLabel: "National Elder-Care NGO",
    careTypes: ["Supports old-age homes", "Mobile healthcare", "Elder helpline"],
    conditionCare: ["Chronic illness (diabetes, hypertension)", "Bedridden care"],
    priceNote:
      "Free / charitable. HQ is administrative; supports 26+ old-age homes and 5 barrier homes nationally.",
    staffCredentials: "Doctors, pharmacists and social workers (mobile units)",
    medicalCapabilities: [
      "159+ mobile healthcare units",
      "Cataract surgeries",
      "Homecare for bedridden elders",
    ],
    hospitalTieUp: "Partner eye hospitals for cataract surgery (official)",
    emergencyPlan: "Elder Helpline 1800-180-1253",
    licensing: ["Registered non-profit (12A, 80G), founded 1978, govt reg. 9270"],
    yearFounded: "1978",
    description: "National headquarters of HelpAge India, an elder-care NGO founded in 1978.",
    longDescription:
      "HelpAge India's Qutab Institutional Area HQ oversees mobile healthcare units, elder helplines and support for 26+ old-age homes nationwide; the address is administrative, not a residential home.",
  },

  // ───────────────────────── MAHARASHTRA ─────────────────────────
  {
    ...base,
    id: "dignity-foundation-mumbai",
    name: "Dignity Foundation (Head Office)",
    neighborhood: "Byculla East",
    city: "Mumbai",
    state: "Maharashtra",
    address:
      "B-206, 2nd Floor, Byculla Service Industries Premises, Dadoji Konddev Marg, Byculla (E), Mumbai 400027",
    phone: "022 6138 1100",
    email: "responsedignity@dignityfoundation.com",
    website: "dignityfoundation.com",
    source: "Official website",
    sourceType: "official",
    listingKind: "office",
    listingNote:
      "Head office / programme address, not a residential home. Dignity Lifestyle retirement township is at Neral.",
    tier: "NGO/Free care",
    tierLabel: "NGO Senior Services HQ",
    careTypes: ["Senior citizen programmes", "Dementia day care"],
    conditionCare: ["Dementia/Alzheimer's"],
    priceNote: "Membership-based; figures N/A.",
    staffCredentials: "Trained caregivers (official)",
    medicalCapabilities: ["Dementia day-care therapies"],
    licensing: ["Registered non-profit, founded 1995"],
    yearFounded: "1995",
    description: "Head office of Dignity Foundation in Byculla East, Mumbai.",
    longDescription:
      "Dignity Foundation's Mumbai HQ coordinates elder-care programmes, helplines and dementia day care across India; residential care is at its separate Dignity Lifestyle township.",
  },
  {
    ...base,
    id: "lsp-mumbai-andheri",
    name: "Little Sisters of the Poor — Home for the Aged",
    neighborhood: "Andheri East (Sher-e-Punjab)",
    city: "Mumbai",
    state: "Maharashtra",
    address:
      "Opp. Canossa Convent Primary School, Prem Vasundhara Society, Mahakali Caves Road, Andheri East, Mumbai 400093",
    phone: "022 2836 4187",
    source: "Secondary (Justdial, Karmayog brochure, AsiaNews)",
    sourceType: "secondary",
    listingNote: "No dedicated official website found; data is from secondary sources.",
    tier: "NGO/Free care",
    tierLabel: "Charitable Home for Aged",
    careTypes: ["Residential care for needy aged (men & women)"],
    conditionCare: ["Chronic illness (diabetes, hypertension)", "Bedridden care"],
    priceNote: 'Charitable — "the only requisites being poverty and old age".',
    amenities: [
      "Infirmaries",
      "Physical therapy on-site",
      "Dental unit",
      "Occupational therapy",
      "Chapel",
    ],
    staffCredentials: "Qualified physician attends; honorary specialists (secondary brochure)",
    medicalCapabilities: [
      "Infirmaries",
      "Physiotherapy",
      "Dental unit",
      "Occupational therapy",
    ],
    emergencyPlan: "Physician in attendance (secondary)",
    cuisine: ["Meals provided"],
    dietary: ["No specific preference"],
    licensing: ["Catholic congregation (Little Sisters of the Poor, founded by Jeanne Jugan)"],
    yearFounded: "1958",
    description:
      "Charitable home for needy elderly men and women in Andheri East, run by the Little Sisters of the Poor since 1958.",
    longDescription:
      "Established in 1958, the home provides free shelter, food, clothing and medical care to poor elderly of all faiths, with infirmaries, physiotherapy and a dental unit.",
  },
  {
    ...base,
    id: "sneha-sadan-vasai",
    name: "Sneha Sadan / Snehasadan Old Age Home",
    neighborhood: "Vasai West",
    city: "Vasai (Palghar district)",
    state: "Maharashtra",
    address: "Sagarshet Petrol Pump Road, Vasai West, Palghar 401201",
    source: "Secondary (Justdial, Sneha Sagar Society)",
    sourceType: "secondary",
    listingNote:
      'No dedicated official website; the name is conflated across "Snehasadan" and "Sneha Sagar" homes — verify the exact entity before publishing.',
    tier: "NGO/Free care",
    tierLabel: "Charitable Old Age Home",
    careTypes: ["Residential care (aged women / destitute)"],
    conditionCare: ["Chronic illness (diabetes, hypertension)", "Bedridden care"],
    priceNote: "Charitable (some homes free for the poor); figures N/A.",
    amenities: ["Shelter", "Meals"],
    staffCredentials: "Sisters, social worker, volunteers, cook (secondary: Sneha Sagar)",
    cuisine: ["Strictly vegetarian"],
    dietary: ["Vegetarian (general)"],
    licensing: ["Sneha Sagar Society registered 2001 (related entity)"],
    description: "Charitable old-age home for destitute elderly in Vasai West, Palghar.",
    longDescription:
      "A church/sisters-run home providing shelter, food and care to senior destitute women in the Vasai area.",
  },
  {
    ...base,
    id: "athashri-bavdhan-pune",
    name: "Athashri Senior Living — Bavdhan (Aastha Pebbles)",
    neighborhood: "Bavdhan",
    city: "Pune",
    state: "Maharashtra",
    address: "Bavdhan, Pune (Aastha assisted living by Athashri Homes Pvt Ltd)",
    website: "aasthaliving.in",
    source: "Official website",
    sourceType: "official",
    tier: "Mid-range assisted living",
    tierLabel: "Assisted Living (Aastha)",
    careTypes: ["Assisted living", "Senior housing"],
    conditionCare: ["Chronic illness (diabetes, hypertension)", "Bedridden care"],
    priceNote:
      "'Aastha' is Athashri's assisted-living arm for dependent seniors; pricing figures N/A.",
    amenities: ["24×7 security", "CCTV", "Housekeeping", "Guest rooms"],
    staffCredentials: "Care staff (Athashri Homes Pvt Ltd)",
    medicalCapabilities: ["Daily-living support for frail and dependent seniors"],
    licensing: ["Athashri Homes Pvt Ltd (sister company of Paranjape Schemes)"],
    residentInterests: ["Yoga", "Meditation", "Games", "Gardens"],
    yearFounded: "Athashri brand 2002",
    description:
      "Athashri/Aastha assisted-living community for dependent seniors in Bavdhan, Pune.",
    longDescription:
      "Aastha Pebbles by Athashri Homes provides assisted living for frail and dependent seniors, a progression from the Athashri senior-housing brand.",
  },

  // ───────────────────────── WEST BENGAL ─────────────────────────
  {
    ...base,
    id: "nirmal-hriday-kolkata",
    name: "Nirmal Hriday (Kalighat Home for the Dying) — Missionaries of Charity",
    neighborhood: "Kalighat",
    city: "Kolkata",
    state: "West Bengal",
    address:
      "251 Kalighat Road, next to Kalighat Kali Temple, Kolkata 700026 (Mother House: 54A A.J.C. Bose Road, Kolkata 700016)",
    website: "missionariesofcharity.org (order-level)",
    source: "Secondary + order website",
    sourceType: "secondary",
    listingNote:
      "No dedicated facility website; a hospice for the dying, not a conventional old-age home.",
    tier: "NGO/Free care",
    tierLabel: "Free Hospice for Dying Destitute",
    careTypes: ["Palliative care", "Hospice care"],
    conditionCare: [
      "Palliative care",
      "Bedridden care",
      "Chronic illness (TB, cancer, HIV/AIDS)",
    ],
    priceNote: "Free hospice for the sick and dying destitute, opened 1952.",
    amenities: ["Dormitory-style beds", "Dining area", "Chapel"],
    staffCredentials: "Nuns (Missionaries of Charity) and volunteers (secondary)",
    medicalCapabilities: ["Basic hygiene care", "Pain relief", "Palliative care"],
    cuisine: ["Meals / feeding provided"],
    dietary: ["No specific preference"],
    licensing: ["Missionaries of Charity (founded by Mother Teresa, 1950)"],
    yearFounded: "1952",
    description:
      "Mother Teresa's first hospice (est. 1952) for the sick and dying destitute, beside Kalighat temple.",
    longDescription:
      "Nirmal Hriday, the Missionaries of Charity's pioneering free hospice, cares for terminally ill and destitute street dwellers with shelter, feeding, pain relief and dignity.",
  },
  {
    ...base,
    id: "shibasram-trust-kolkata",
    name: "Shibasram Trust (Shibasram Old Age Home)",
    neighborhood: "Santoshpur (Survey Park)",
    city: "Kolkata",
    state: "West Bengal",
    address: "1250, P G Survey Park, Survey Park, Santoshpur, Kolkata 700075",
    phone: "+91-99038 14392 / +91-8697407135",
    email: "shibasram@gmail.com",
    website: "shibasram.org.in",
    source: "Official website",
    sourceType: "official",
    tier: "Budget/Private",
    tierLabel: "Assisted Living & Memory Care",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Nursing care",
      "Palliative / end-of-life care",
      "Respite / day care",
      "Home care",
    ],
    conditionCare: [
      "Dementia/Alzheimer's",
      "Palliative care",
      "Bedridden care",
      "Chronic illness (diabetes, hypertension)",
    ],
    priceNote: "Site cites 'affordable, transparent pricing' with no rupee figure published.",
    deposit: "Refundable security deposit (official; amount N/A)",
    amenities: ["Dining", "Private and shared rooms", "Activities", "Female-only wing"],
    staffCredentials: "Nursing and medical staff (official)",
    medicalCapabilities: [
      "24/7 nursing and medical care",
      "Physiotherapy",
      "Speech/swallow therapy",
      "Palliative care",
    ],
    hospitalTieUp:
      "No formal tie-up; cites proximity to AMRI, Apollo, B.M. Birla Heart, CMRI and Medica (official)",
    emergencyPlan: "On-call doctors and emergency ambulance (official)",
    cuisine: ["Meals provided"],
    licensing: ["Registered under the Indian Trusts Act (official; number N/A)"],
    residentInterests: ["Activities", "Durga Puja celebrations"],
    trialStay: "Respite and day care available (official); terms N/A",
    yearFounded: "2013 (official)",
    description: "Trust-run assisted-living and dementia care home in Santoshpur, Kolkata (since 2013).",
    longDescription:
      "Shibasram offers assisted living, specialised memory care, 24/7 nursing, physiotherapy and palliative care with a female-only wing and proximity to major Kolkata hospitals.",
  },

  // ───────────────────────── GUJARAT ─────────────────────────
  {
    ...base,
    id: "kadji-care-vadodara",
    name: "Kadji Care and Rehabs Pvt Ltd",
    neighborhood: "Kalali",
    city: "Vadodara",
    state: "Gujarat",
    address: "Kadji Road, next to Delhi Public School, Vadsar, Kalali, Vadodara 390020",
    phone: "+91 9403890406",
    email: "info@kadji.co.in",
    website: "kadji.co.in",
    source: "Official website + secondary (ElderCasa, Jeevin, Sulekha)",
    sourceType: "official",
    tier: "Budget/Private",
    tierLabel: "Rehab-focused Assisted Living",
    careTypes: [
      "Assisted living",
      "Memory/dementia care",
      "Stroke / coma / Parkinson's rehabilitation",
      "Post-operative rehabilitation",
      "Cancer & cardiac care",
      "Palliative care",
    ],
    conditionCare: [
      "Post-surgery recovery",
      "Paralysis",
      "Dementia/Alzheimer's",
      "Palliative care",
      "Bedridden care",
      "Chronic illness (diabetes, hypertension)",
    ],
    priceMin: 45000,
    priceMax: 60000,
    priceNote:
      "~₹1,500/day (Basic) to ~₹2,000/day (Premium, excl. consumables) — roughly ₹45,000–₹60,000/mo (secondary: ElderCasa).",
    itemizedCosts: [
      { name: "Basic package", cost: "~₹1,500/day (secondary)" },
      { name: "Premium package", cost: "~₹2,000/day, excl. consumables (secondary)" },
    ],
    amenities: [
      "AC rooms with 2 beds",
      "TV",
      "Physiotherapy machinery",
      "Common hall",
      "Outdoor space",
    ],
    staffRatio: "70+ team members (secondary: Sulekha); resident-to-staff ratio N/A",
    staffCredentials: "Doctors, nurses, physiotherapists, rehab specialists (official)",
    medicalCapabilities: [
      "Weekly doctor check-ups",
      "Daily vitals",
      "Oxygen therapy",
      "Nebulisers",
      "Suction therapy",
      "Specialists on call",
    ],
    emergencyPlan: "Emergency medications and oxygen on site (secondary)",
    cuisine: ["Daily vegetarian meals planned by a diet specialist"],
    dietary: ["Vegetarian (general)"],
    licensing: ["Kadji Care and Rehabs Pvt Ltd, founded 2012 (secondary)"],
    residentInterests: ["Ball games", "Brain games", "Garden walks", "Antakshari", "Carrom"],
    trialStay: "Short-stay and long-stay options (secondary); terms N/A",
    yearFounded: "2012",
    description:
      "Medically-assisted rehab and elder-care home in Kalali, Vadodara (est. 2012).",
    longDescription:
      "Kadji Care offers rehab-focused assisted living for stroke, Parkinson's, coma, dementia and post-operative recovery with physiotherapy, oxygen therapy and vegetarian meals on Basic/Premium daily packages.",
  },
  {
    ...base,
    id: "athashri-vadodara",
    name: "Athashri Senior Living — Vadodara",
    neighborhood: "Vadodara",
    city: "Vadodara",
    state: "Gujarat",
    address: "Vadodara (Athashri Vadodara by Paranjape Schemes; full postal N/A)",
    website: "pscl.in/projects/senior-living/athashri-vadodara",
    source: "Official website",
    sourceType: "official",
    listingNote:
      "'Forest Trails' is a Paranjape township in Bavdhan, Pune; the Vadodara Athashri is a separate project — verify exact naming before publishing.",
    tier: "Mid-range assisted living",
    tierLabel: "Senior Living Community",
    careTypes: ["Independent living"],
    conditionCare: [],
    amenities: [
      "Grab bars in all toilets",
      "Shower seat",
      "Modular switches",
      "Energy-efficient fixtures",
      "Green living features",
    ],
    medicalCapabilities: ["Senior-friendly design (grab bars, shower seats)"],
    licensing: ["Paranjape / Athashri brand"],
    yearFounded: "Athashri brand 2002",
    description: "Eco-friendly Athashri senior-living community in Vadodara by Paranjape Schemes.",
    longDescription:
      "Athashri Vadodara offers senior-friendly apartments with grab bars, shower seats and green-living features, part of the Athashri brand.",
  },

  // ───────────────────────── KERALA ─────────────────────────
  {
    ...base,
    id: "bethany-home-thiruvananthapuram",
    name: "Bethany Home for the Aged (Bethel Gram, CSI South Kerala Diocese)",
    neighborhood: "Mukkola / Kallayam",
    city: "Thiruvananthapuram",
    state: "Kerala",
    address:
      "Bethel Gram, Dr. Frederick Road, Mukkola, Kallayam P.O., Thiruvananthapuram 695043",
    phone: "0471 2371901 (also 2437901 / 2315781)",
    website: "bethelgram.org (likely official; could not be verified live)",
    source: "Secondary (government registry, directories, YouTube)",
    sourceType: "secondary",
    listingNote:
      "Official website (bethelgram.org) could not be verified live; data is from secondary sources.",
    tier: "NGO/Free care",
    tierLabel: "Charitable Old Age Home",
    careTypes: ["Residential elder care (men & women)"],
    conditionCare: ["Chronic illness (diabetes, hypertension)", "Bedridden care"],
    priceNote: "Charitable, church-run; capacity ~50–60. Figures N/A.",
    languages: ["Malayalam"],
    licensing: ["Kerala govt old-age-home registry #1606", "CSI South Kerala Diocese"],
    yearFounded: "Government-registered as an old-age home on 01/12/2009",
    description: "Church-run charitable old-age home for men and women in Thiruvananthapuram.",
    longDescription:
      "Bethany Home for the Aged (Bethel Gram), run by the CSI South Kerala Diocese, is a government-registered charitable home for elderly men and women in Mukkola/Kallayam.",
  },
  {
    ...base,
    id: "athulya-kakkanad-kochi",
    name: "Athulya Senior Care — Kakkanad",
    neighborhood: "Kakkanad",
    city: "Kochi",
    state: "Kerala",
    address: "Kakkanad, Kochi (postal N/A)",
    phone: "+91 98849 45900 (company-wide)",
    website: "athulyaseniorcare.com/location/kochi",
    source: "Official website (company-wide detail only)",
    sourceType: "official",
    listingNote: "Branch-specific page detail is thin.",
    tier: "Premium/Medical care",
    tierLabel: "Premium Assisted Living",
    careTypes: ATHULYA_CARE,
    conditionCare: ATHULYA_CONDITIONS,
    amenities: ["Senior-friendly infrastructure (company-wide)"],
    medicalCapabilities: ["24/7 nursing", "Physiotherapy"],
    licensing: ["JCI/NABH-inspired standards (company-wide, not a certification)"],
    yearFounded: "Athulya brand founded 2016",
    description: "Athulya assisted-living facility in Kakkanad, Kochi.",
    longDescription:
      "Athulya's Kochi branch offering assisted living, memory care, rehabilitation and palliative care under clinical supervision.",
  },

  // ───────────────────────── TELANGANA ─────────────────────────
  {
    ...base,
    id: "means-elders-care-hyderabad",
    name: "MEANS Elders Care (Medical Educational and Nature Service)",
    neighborhood: "Ramgopalpet / Moula Ali",
    city: "Hyderabad",
    state: "Telangana",
    address:
      "5-277, Krishna Nagar, NFC Main Road, Moula Ali, Hyderabad 500040 (also listed 5-227, Krishna Nagar Colony, ECIL X Roads, Ramgopalpet 500040)",
    phone: "+91-40 27242528 / 9700006699",
    email: "meanshomes@gmail.com",
    website: "meansindia.in",
    source: "Official website + secondary (Sulekha)",
    sourceType: "official",
    tier: "NGO/Free care",
    tierLabel: "Free Elder Care NGO",
    careTypes: [
      "Free residential care (abandoned, bedridden, destitute, mentally-ill elders)",
      "Nursing care",
      "Palliative care",
    ],
    conditionCare: [
      "Paralysis",
      "Chronic illness (diabetes, hypertension)",
      "Palliative care",
      "Bedridden care",
      "Dementia/Alzheimer's",
    ],
    priceNote:
      "Free. Sponsor-an-elder at ₹5,000/month is a donation, not a resident fee. Two homes, 150+ residents.",
    deposit: "None",
    amenities: ["Shelter", "Food", "Medical care", "Emotional support"],
    staffCredentials: "Doctors and nursing staff (official)",
    medicalCapabilities: [
      "Round-the-clock medical attention",
      "Chronic and post-operative care",
      "Counselling / psychiatric care",
    ],
    emergencyPlan: "24/7 medical attention (official)",
    cuisine: ["Nutritious meals provided"],
    languages: ["Telugu"],
    licensing: ["Registered non-profit, reg. no. 5671/1994 (secondary: Sulekha)"],
    yearFounded: "Registered 1994; founded by Dr. O.G. (Gnana) Prakash",
    description:
      "Free NGO home in Hyderabad for poor, abandoned, bedridden and mentally-ill elders (150+ residents).",
    longDescription:
      "MEANS (reg. 5671/1994) provides free shelter, food, round-the-clock medical care and emotional support for destitute elders across two Hyderabad homes.",
  },
  {
    ...base,
    id: "athulya-kukatpally-hyderabad",
    name: "Athulya Senior Care — Kukatpally",
    neighborhood: "Kukatpally",
    city: "Hyderabad",
    state: "Telangana",
    address: "Kukatpally, Hyderabad (postal N/A)",
    phone: "+91 98849 45900 (company-wide)",
    website: "athulyaseniorcare.com/location/hyderabad",
    source: "Official website (company-wide detail only)",
    sourceType: "official",
    listingNote: "Branch-specific page detail is thin.",
    tier: "Premium/Medical care",
    tierLabel: "Premium Assisted Living",
    careTypes: ATHULYA_CARE,
    conditionCare: ATHULYA_CONDITIONS,
    amenities: ["Senior-friendly infrastructure (company-wide)"],
    medicalCapabilities: ["24/7 nursing", "Physiotherapy"],
    licensing: ["JCI/NABH-inspired standards (company-wide, not a certification)"],
    yearFounded: "Athulya brand founded 2016",
    description: "Athulya assisted-living facility in Kukatpally, Hyderabad.",
    longDescription:
      "Athulya's Hyderabad branch offering assisted living, memory care, rehabilitation and palliative care under clinical supervision.",
  },

  // ───────────────────────── UTTAR PRADESH ─────────────────────────
  {
    ...base,
    id: "antara-noida",
    name: "Antara Senior Living — Noida (Max Estate)",
    neighborhood: "Sector 150",
    city: "Noida",
    state: "Uttar Pradesh",
    address: "Sector 150, Noida (near the Noida–Greater Noida Expressway)",
    website: "antaraseniorcare.com/senior-living-residence/noida",
    source: "Official website + secondary (SquareYards, RERA)",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Independent Senior Living",
    careTypes: ["Independent living (2/3/4 BHK)", "Continuous care"],
    conditionCare: [],
    priceMin: 11300000,
    priceNote:
      "From ₹1.13 Cr (2 BHK entry, secondary). ~540 units across 5 towers; Phase I OC covers 3 towers / 340 units; possession from June 2025 (RERA UPRERAPRJ745377).",
    itemizedCosts: [
      {
        name: "Antara Comprehensive Benefit (monthly service charge)",
        cost: "₹40,000 – ₹1,13,000/mo depending on apartment size and services opted (official)",
      },
    ],
    amenities: [
      "Antara Club",
      "Panic alarms",
      "Wider doors",
      "Large windows",
      "Two-way switches",
    ],
    medicalCapabilities: [
      "Continuous care",
      "Panic alarms",
      "Anti-skid flooring",
      "Wheelchair turning radius",
    ],
    distanceToHospital: "Apollo Hospital 3.07 km (secondary: SquareYards)",
    emergencyPlan: "Panic alarm buttons (official)",
    cuisine: ["Dining services"],
    licensing: ["RERA UPRERAPRJ745377", "Max Group"],
    residentInterests: ["Active-ageing club"],
    yearFounded: "Antara founded 2011",
    description:
      "Max Group's luxury independent senior-living community in Sector 150, Noida (possession June 2025).",
    longDescription:
      "Antara Senior Living Noida offers 2–4 BHK senior residences (from ₹1.13 Cr) with the Antara Comprehensive Benefit service package (₹40k–₹1.13L/mo), senior-specific safety design and the Antara Club.",
  },

  // ───────────────────────── UTTARAKHAND ─────────────────────────
  {
    ...base,
    id: "antara-dehradun",
    name: "Antara Senior Living — Purukul, Dehradun",
    neighborhood: "Purukul",
    city: "Dehradun",
    state: "Uttarakhand",
    address: "Purukul, Dehradun (14-acre campus in the wellness/tourism zone)",
    website: "antaraseniorcare.com/senior-living-residence",
    source: "Official website + secondary (Jeevin, Wikipedia)",
    sourceType: "official",
    tier: "Premium/Medical care",
    tierLabel: "Luxury Independent Senior Living",
    careTypes: ["Independent living (apartments 1400+ sqft)", "Preventive & reactive healthcare"],
    conditionCare: [],
    priceMin: 20000000,
    priceMax: 80000000,
    priceNote:
      "~₹2 Cr – ₹8 Cr apartment ticket range (secondary: Jeevin); 190 apartments on 14 acres; monthly charges from ~₹50K (secondary).",
    itemizedCosts: [
      {
        name: "Antara Comprehensive Benefit (monthly)",
        cost: "₹33,399 – ₹1,06,213/mo (official: max-antara.co.in)",
      },
    ],
    amenities: [
      "Antara Club",
      "Age-appropriate materials, colours and fixtures",
      "Outdoor space",
    ],
    medicalCapabilities: ["Preventive & reactive healthcare", "Senior-specific fixtures"],
    hospitalTieUp: "Max Super Specialty Hospital a short drive away (official)",
    cuisine: ["Dining services"],
    licensing: ["Max Group"],
    residentInterests: ["Active-ageing club"],
    yearFounded: "Antara founded 2011",
    description: "Antara's flagship 14-acre luxury senior-living community in Purukul, Dehradun.",
    longDescription:
      "Antara Dehradun (Max Group), spread over 14 acres with 190 apartments, offers independent senior living with preventive/reactive healthcare, the Antara Comprehensive Benefit package and Max Super Specialty Hospital nearby.",
  },
];

/** Fields we consider "fillable" for the internal completeness score. */
export function specCompleteness(sp: RealFacilitySpec): number {
  const checks: boolean[] = [
    !!sp.address && !sp.address.includes("postal N/A"),
    !!sp.phone,
    !!sp.email,
    !!sp.website,
    sp.priceMin > 0 || sp.priceMax > 0,
    sp.itemizedCosts.length > 0,
    sp.deposit !== NA,
    sp.amenities.length > 0,
    sp.staffRatio !== NA,
    sp.staffCredentials !== NA,
    sp.medicalCapabilities.length > 0,
    sp.hospitalTieUp !== NA,
    sp.distanceToHospital !== NA,
    sp.distanceToAirport !== NA,
    sp.emergencyPlan !== NA,
    sp.cuisine.length > 0,
    sp.dietary.length > 0,
    sp.languages.length > 0,
    sp.licensing.length > 0,
    sp.residentInterests.length > 0,
    sp.trialStay !== NA,
    sp.petFriendly !== NA,
    sp.distantFamilySupport !== NA,
    sp.yearFounded !== NA,
  ];
  return Math.round((checks.filter(Boolean).length / checks.length) * 100);
}
