/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterFacilityRouteImport } from './routes/register-facility'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FounderAccessRouteImport } from './routes/founder-access'
import { Route as FacilityLoginRouteImport } from './routes/facility-login'
import { Route as FacilityAccessRouteImport } from './routes/facility-access'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as FacilityIdRouteImport } from './routes/facility.$id'
import { Route as FacilityClaimIdRouteImport } from './routes/facility-claim.$id'
import { Route as DashboardVerificationRouteImport } from './routes/dashboard.verification'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterFacilityRoute = RegisterFacilityRouteImport.update({
  id: '/register-facility',
  path: '/register-facility',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderAccessRoute = FounderAccessRouteImport.update({
  id: '/founder-access',
  path: '/founder-access',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityLoginRoute = FacilityLoginRouteImport.update({
  id: '/facility-login',
  path: '/facility-login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityAccessRoute = FacilityAccessRouteImport.update({
  id: '/facility-access',
  path: '/facility-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const FacilityIdRoute = FacilityIdRouteImport.update({
  id: '/facility/$id',
  path: '/facility/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityClaimIdRoute = FacilityClaimIdRouteImport.update({
  id: '/facility-claim/$id',
  path: '/facility-claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerificationRoute = DashboardVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/facility-access': typeof FacilityAccessRoute
  '/facility-login': typeof FacilityLoginRoute
  '/founder-access': typeof FounderAccessRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/register-facility': typeof RegisterFacilityRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/facility-claim/$id': typeof FacilityClaimIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/facility-access': typeof FacilityAccessRoute
  '/facility-login': typeof FacilityLoginRoute
  '/founder-access': typeof FounderAccessRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/register-facility': typeof RegisterFacilityRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/facility-claim/$id': typeof FacilityClaimIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/facility-access': typeof FacilityAccessRoute
  '/facility-login': typeof FacilityLoginRoute
  '/founder-access': typeof FounderAccessRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/register-facility': typeof RegisterFacilityRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/facility-claim/$id': typeof FacilityClaimIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/facility-access'
    | '/facility-login'
    | '/founder-access'
    | '/home'
    | '/profile'
    | '/questionnaire'
    | '/register-facility'
    | '/search'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/insights'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/verification'
    | '/facility-claim/$id'
    | '/facility/$id'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/facility-access'
    | '/facility-login'
    | '/founder-access'
    | '/home'
    | '/profile'
    | '/questionnaire'
    | '/register-facility'
    | '/search'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/insights'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/verification'
    | '/facility-claim/$id'
    | '/facility/$id'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/facility-access'
    | '/facility-login'
    | '/founder-access'
    | '/home'
    | '/profile'
    | '/questionnaire'
    | '/register-facility'
    | '/search'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/insights'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/verification'
    | '/facility-claim/$id'
    | '/facility/$id'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FacilityAccessRoute: typeof FacilityAccessRoute
  FacilityLoginRoute: typeof FacilityLoginRoute
  FounderAccessRoute: typeof FounderAccessRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  RegisterFacilityRoute: typeof RegisterFacilityRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FacilityClaimIdRoute: typeof FacilityClaimIdRoute
  FacilityIdRoute: typeof FacilityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-facility': {
      id: '/register-facility'
      path: '/register-facility'
      fullPath: '/register-facility'
      preLoaderRoute: typeof RegisterFacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-access': {
      id: '/founder-access'
      path: '/founder-access'
      fullPath: '/founder-access'
      preLoaderRoute: typeof FounderAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility-login': {
      id: '/facility-login'
      path: '/facility-login'
      fullPath: '/facility-login'
      preLoaderRoute: typeof FacilityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility-access': {
      id: '/facility-access'
      path: '/facility-access'
      fullPath: '/facility-access'
      preLoaderRoute: typeof FacilityAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/facility/$id': {
      id: '/facility/$id'
      path: '/facility/$id'
      fullPath: '/facility/$id'
      preLoaderRoute: typeof FacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility-claim/$id': {
      id: '/facility-claim/$id'
      path: '/facility-claim/$id'
      fullPath: '/facility-claim/$id'
      preLoaderRoute: typeof FacilityClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verification': {
      id: '/dashboard/verification'
      path: '/verification'
      fullPath: '/dashboard/verification'
      preLoaderRoute: typeof DashboardVerificationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardVerificationRoute: typeof DashboardVerificationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardVerificationRoute: DashboardVerificationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FacilityAccessRoute: FacilityAccessRoute,
  FacilityLoginRoute: FacilityLoginRoute,
  FounderAccessRoute: FounderAccessRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  RegisterFacilityRoute: RegisterFacilityRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FacilityClaimIdRoute: FacilityClaimIdRoute,
  FacilityIdRoute: FacilityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
